{
    "terminal.integrated.shellIntegration.showCommandGuide": false,
   "terminal.integrated.profiles.linux": {
    "zsh": {
        "path": "/usr/bin/flatpak-spawn",
        "args": [
            "--host",
            "--watch-bus",
            "--env=TERM=xterm-256color",
            "zsh"
        ],
        "overrideName": true
    }
    },
    "terminal.integrated.defaultProfile.linux": "zsh",
    "json.schemas": [],
    "workbench.editor.empty.hint": "hidden",
    "workbench.secondarySideBar.defaultVisibility": "visible",
    "workbench.colorTheme": "Vira Carbon",
    "workbench.colorCustomizations": {
        "[Vira*]": {
            "statusBar.debuggingBackground": "#80CBC433",
            "statusBar.debuggingForeground": "#80CBC4",
            "toolbar.activeBackground": "#80CBC426",
            "button.background": "#80CBC4",
            "button.hoverBackground": "#80CBC4cc",
            "extensionButton.separator": "#80CBC433",
            "extensionButton.background": "#80CBC414",
            "extensionButton.foreground": "#80CBC4",
            "extensionButton.hoverBackground": "#80CBC433",
            "extensionButton.prominentForeground": "#80CBC4",
            "extensionButton.prominentBackground": "#80CBC414",
            "extensionButton.prominentHoverBackground": "#80CBC433",
            "activityBarBadge.background": "#80CBC4",
            "activityBar.activeBorder": "#80CBC4",
            "activityBarTop.activeBorder": "#80CBC4",
            "list.inactiveSelectionIconForeground": "#80CBC4",
            "list.activeSelectionForeground": "#80CBC4",
            "list.inactiveSelectionForeground": "#80CBC4",
            "list.highlightForeground": "#80CBC4",
            "sash.hoverBorder": "#80CBC480",
            "list.activeSelectionIconForeground": "#80CBC4",
            "scrollbarSlider.activeBackground": "#80CBC480",
            "editorSuggestWidget.highlightForeground": "#80CBC4",
            "textLink.foreground": "#80CBC4",
            "progressBar.background": "#80CBC4",
            "pickerGroup.foreground": "#80CBC4",
            "tab.activeBorder": "#80CBC4",
            "tab.activeBorderTop": "#80CBC400",
            "tab.unfocusedActiveBorder": "#80CBC4",
            "tab.unfocusedActiveBorderTop": "#80CBC400",
            "tab.activeModifiedBorder": "#80CBC400",
            "notificationLink.foreground": "#80CBC4",
            "editorWidget.resizeBorder": "#80CBC4",
            "editorWidget.border": "#80CBC4",
            "settings.modifiedItemIndicator": "#80CBC4",
            "panelTitle.activeBorder": "#80CBC4",
            "breadcrumb.activeSelectionForeground": "#80CBC4",
            "menu.selectionForeground": "#80CBC4",
            "menubar.selectionForeground": "#80CBC4",
            "editor.findMatchBorder": "#80CBC4",
            "selection.background": "#80CBC440",
            "statusBarItem.remoteBackground": "#80CBC414",
            "statusBarItem.remoteHoverBackground": "#80CBC4",
            "statusBarItem.remoteForeground": "#80CBC4",
            "notebook.inactiveFocusedCellBorder": "#80CBC480",
            "commandCenter.activeBorder": "#80CBC480",
            "chat.slashCommandForeground": "#80CBC4",
            "chat.avatarForeground": "#80CBC4",
            "activityBarBadge.foreground": "#000000",
            "button.foreground": "#000000",
            "statusBarItem.remoteHoverForeground": "#000000"
        }
    },
    "workbench.iconTheme": "vira-icons-carbon",
    "42header.email": "tlaghzal@student.1337.ma",
    "42header.username": "tlaghzal",
    "files.autoSave": "afterDelay",
    "editor.fontFamily": "'SF Mono','Droid Sans Mono', 'monospace', monospace",
    "python.analysis.typeCheckingMode": "standard",
    "github.copilot.nextEditSuggestions.enabled": true,
    "editor.minimap.enabled": false,
    "files.exclude": {
        "**/.trunk/*actions/": true,
        "**/.trunk/*logs/": true,
        "**/.trunk/*notifications/": true,
        "**/.trunk/*out/": true,
        "**/.trunk/*plugins/": true
    },
    "files.watcherExclude": {
        "**/.trunk/*actions/": true,
        "**/.trunk/*logs/": true,
        "**/.trunk/*notifications/": true,
        "**/.trunk/*out/": true,
        "**/.trunk/*plugins/": true
    },
    "explorer.confirmDelete": false,
    "workbench.sideBar.location": "right",
    "workbench.activityBar.location": "top",
    "workbench.productIconTheme": "viraUIIcons",
    "github.copilot.enable": {
        "*": true,
        "plaintext": false,
        "markdown": false,
        "scminput": false,
        "python": false
    },
    "viraTheme.accent": "Teal",
    "chat.viewSessions.enabled": false
}