color0 #161616
color1 #ef8585
color2 #a3c99c
color3 #d6bf8f
color4 #91b4d5
color5 #bda3d1
color6 #91c7c7
color7 #dddddd
color8 #666666
color9 #ef8585
color10 #a3c99c
color11 #d6bf8f
color12 #91b4d5
color13 #bda3d1
color14 #91c7c7
color15 #ffffff

cursor                #dddddd
cursor_text_color     #000000
background            #000000
foreground            #dddddd
selection_foreground  #ffffff
selection_background  #303030
active_border_color   #cccccc
inactive_border_color #101010
url_color             #cccccc

active_tab_foreground   #000000
active_tab_background   #cccccc
inactive_tab_foreground #bbbbbb
inactive_tab_background #101010
cursor_trail_color      #bbbbbb
