-- Perfect Black — standalone colorscheme for Neovim ≥ 0.11
-- Pure black canvas, crimson accents, high-contrast syntax.
-- Converts the previous onedark.nvim override into a native colorscheme,
-- eliminating the third-party dependency entirely.

if vim.g.colors_name then vim.cmd('hi clear') end
vim.g.colors_name = 'perfect-black'
vim.o.termguicolors = true
vim.o.background = 'dark'

-- ── Palette ────────────────────────────────────────────────────────────
local p = {
  black   = '#000000',
  bg0     = '#000000', bg_d = '#0A0A0A', bg1 = '#141414',
  bg2     = '#1E1E1E', bg3 = '#2A2A2A',
  fg      = '#D7E3FF', grey = '#53627A', light_grey = '#A9B9D6',
  blue    = '#69AFFF', green = '#B8E986', purple = '#C7A6FF',
  red     = '#FF8FA3', orange = '#FF9E64', yellow = '#FFD166', cyan = '#70D7FF',
}

-- ── Helpers ────────────────────────────────────────────────────────────
--- Convert an onedark-style {fg, bg, fmt, sp} table into native nvim_set_hl attrs.
local function resolve(spec)
  if not spec or type(spec) ~= 'table' then return spec end
  local out = {}
  -- Resolve $variable references against the palette
  for _, key in ipairs({ 'fg', 'bg', 'sp' }) do
    local v = spec[key]
    if type(v) == 'string' and v:sub(1, 1) == '$' then
      out[key] = p[v:sub(2)]
    elseif v and v ~= 'NONE' then
      out[key] = v
    end
  end
  -- Convert fmt string to boolean attributes
  local fmt = spec.fmt
  if fmt then
    for token in fmt:gmatch('[^,]+') do
      local t = token:match('^%s*(.-)%s*$')
      if     t == 'bold'          then out.bold = true
      elseif t == 'italic'        then out.italic = true
      elseif t == 'underline'     then out.underline = true
      elseif t == 'undercurl'     then out.undercurl = true
      elseif t == 'strikethrough' then out.strikethrough = true
      end
    end
  end
  -- Pass through any native keys already present
  for _, key in ipairs({ 'bold', 'italic', 'underline', 'undercurl', 'strikethrough', 'link', 'default' }) do
    if spec[key] ~= nil and out[key] == nil then out[key] = spec[key] end
  end
  return out
end

local function hi(name, spec) vim.api.nvim_set_hl(0, name, resolve(spec)) end
local function groups(names, spec)
  for name in names:gmatch('%S+') do hi(name, spec) end
end

-- ── Editor Chrome ──────────────────────────────────────────────────────
hi('Normal',       { fg = p.fg, bg = p.bg0 })
hi('NormalNC',     { bg = '$bg_d' })
hi('NormalFloat',  { bg = '$bg1', fg = p.fg })
hi('Comment',      { fg = '#61708A', fmt = 'italic' })
hi('SpecialComment', { fg = '#61708A', fmt = 'italic' })
hi('LineNr',       { fg = '#555555', bg = 'NONE' })
hi('CursorLine',   { bg = '#180A0E' })
hi('CursorLineNr', { fg = '#FF2E4C', bg = 'NONE', fmt = 'bold' })
hi('Cursor',       { fg = '#000000', bg = '#FF2E4C' })
hi('lCursor',      { fg = '#000000', bg = '#FF2E4C' })
hi('MatchParen',   { fg = '#FFFFFF', bg = '#5C1522', fmt = 'bold,underline' })
hi('Substitute',   { bg = '#FF2E4C', fg = p.bg0, fmt = 'bold' })
hi('Folded',       { fg = p.grey, bg = p.bg1, fmt = 'italic' })
hi('FoldColumn',   { fg = p.grey, bg = 'NONE' })
hi('EndOfBuffer',  { fg = p.bg0, bg = 'NONE' })
hi('StatusLine',   { bg = p.bg1, fg = p.fg })
hi('StatusLineNC', { bg = p.bg_d, fg = p.grey })
hi('WinBar',       { bg = p.bg0, fg = p.light_grey, fmt = 'bold' })
hi('WinBarNC',     { bg = p.bg0, fg = p.grey })
hi('TabLine',      { bg = p.bg1, fg = p.grey })
hi('TabLineFill',  { bg = p.bg0 })
hi('TabLineSel',   { bg = '#3D0D14', fg = p.fg, fmt = 'bold' })
hi('FloatBorder',  { bg = p.bg1, fg = '#5C1522' })
hi('FloatTitle',   { bg = p.bg1, fg = '#FF2E4C', fmt = 'bold' })
hi('Pmenu',        { bg = p.bg1, fg = p.fg })
hi('PmenuSel',     { bg = '#4A0E17', fg = '#FF4D6D', fmt = 'bold' })
hi('PmenuBorder',  { fg = '#5C1522', bg = p.bg1 })
hi('PmenuSbar',    { bg = '#0A0A0E' })
hi('PmenuThumb',   { bg = '#5C1522' })
hi('WinSeparator', { fg = '#3D101A', bg = p.bg0 })
hi('MsgArea',      { fg = p.fg, bg = p.bg0 })
hi('MsgSeparator', { fg = p.bg3, bg = p.bg0 })
hi('NonText',      { fg = '#61708A' })
hi('Whitespace',   { fg = '#4A4A5A' })
hi('Directory',    { fg = '#FF4D6D', fmt = 'bold' })
hi('Title',        { fg = '#FF2E4C', fmt = 'bold' })
hi('Question',     { fg = p.green, fmt = 'bold' })
hi('MoreMsg',      { fg = p.green, fmt = 'bold' })
hi('WarningMsg',   { fg = p.yellow, fmt = 'bold' })
hi('ErrorMsg',     { fg = p.red, fmt = 'bold' })
hi('WildMenu',     { bg = p.bg2, fg = p.purple, fmt = 'bold' })
hi('SignColumn',   { bg = 'NONE' })
hi('ColorColumn',  { bg = p.bg1 })
hi('Conceal',      { fg = p.grey })
hi('SpecialKey',   { fg = p.grey })
hi('VertSplit',    { fg = '#3D101A', bg = p.bg0 })

-- ── Standard Vim Syntax ────────────────────────────────────────────────
hi('Constant',     { fg = '#FACC15' })
hi('String',       { fg = '#4ADE80' })
hi('Character',    { fg = '#4ADE80' })
hi('Number',       { fg = '#FF9E64' })
hi('Boolean',      { fg = '#FF9E64', fmt = 'bold' })
hi('Float',        { fg = '#FF9E64' })
hi('Identifier',   { fg = '#E2E8F0' })
hi('Function',     { fg = '#38BDF8' })
hi('Statement',    { fg = '#D946EF', fmt = 'bold' })
hi('Conditional',  { fg = '#C084FC', fmt = 'bold' })
hi('Repeat',       { fg = '#C084FC', fmt = 'bold' })
hi('Label',        { fg = '#FFD166', fmt = 'bold' })
hi('Operator',     { fg = '#70D7FF' })
hi('Keyword',      { fg = '#D946EF', fmt = 'bold' })
hi('Exception',    { fg = '#FF2E4C', fmt = 'bold' })
hi('PreProc',      { fg = '#FF4D6D', fmt = 'bold' })
hi('Include',      { fg = '#E879F9', fmt = 'bold' })
hi('Define',       { fg = '#FF4D6D', fmt = 'bold' })
hi('Macro',        { fg = '#FF4D6D' })
hi('PreCondit',    { fg = '#D946EF', fmt = 'bold' })
hi('Type',         { fg = '#FFD166' })
hi('StorageClass', { fg = '#D946EF', fmt = 'bold' })
hi('Structure',    { fg = '#FFD166', fmt = 'bold' })
hi('Typedef',      { fg = '#FFD166', fmt = 'bold' })
hi('Special',      { fg = '#FF4D6D' })
hi('SpecialChar',  { fg = '#F97316' })
hi('Delimiter',    { fg = '#94A3B8' })

-- ── Treesitter Base Captures ───────────────────────────────────────────
hi('@variable',            { fg = '#E2E8F0' })
hi('@variable.parameter',  { fg = '#FF9E64' })
hi('@variable.member',     { fg = '#C084FC' })
hi('@variable.builtin',    { fg = '#FF4D6D' })
hi('@property',            { fg = '#C084FC' })
hi('@field',               { fg = '#C084FC' })
hi('@function',            { fg = '#38BDF8' })
hi('@function.call',       { fg = '#38BDF8' })
hi('@function.method',     { fg = '#22D3EE' })
hi('@function.method.call', { fg = '#22D3EE' })
hi('@function.builtin',    { fg = '#FF4D6D' })
hi('@function.macro',      { fg = '#FF4D6D' })
hi('@method',              { fg = '#22D3EE' })
hi('@method.call',         { fg = '#22D3EE' })
hi('@constructor',         { fg = '#FFD166', fmt = 'bold' })
hi('@type',                { fg = '#FFD166' })
hi('@type.builtin',        { fg = '#FBBF24', fmt = 'bold' })
hi('@type.definition',     { fg = '#FFD166', fmt = 'bold' })
hi('@type.qualifier',      { fg = '#D946EF', fmt = 'bold' })
hi('@class',               { fg = '#FFD166', fmt = 'bold' })
hi('@interface',           { fg = '#FFD166', fmt = 'bold' })
hi('@struct',              { fg = '#FFD166', fmt = 'bold' })
hi('@enum',                { fg = '#FFD166', fmt = 'bold' })
hi('@enumMember',          { fg = '#F59E0B' })
hi('@string',              { fg = '#4ADE80' })
hi('@string.regex',        { fg = '#F97316' })
hi('@string.regexp',       { fg = '#F97316' })
hi('@string.escape',       { fg = '#F97316' })
hi('@string.special',      { fg = '#4ADE80' })
hi('@character',           { fg = '#4ADE80' })
hi('@character.special',   { fg = '#F97316' })
hi('@number',              { fg = '#FF9E64' })
hi('@number.float',        { fg = '#FF9E64' })
hi('@float',               { fg = '#FF9E64' })
hi('@boolean',             { fg = '#FF9E64', fmt = 'bold' })
hi('@constant',            { fg = '#FACC15' })
hi('@constant.builtin',    { fg = '#FACC15', fmt = 'bold' })
hi('@keyword',             { fg = '#D946EF', fmt = 'bold' })
hi('@keyword.coroutine',   { fg = '#D946EF', fmt = 'bold' })
hi('@keyword.function',    { fg = '#D946EF', fmt = 'bold' })
hi('@keyword.operator',    { fg = '#D946EF', fmt = 'bold' })
hi('@keyword.import',      { fg = '#E879F9', fmt = 'bold' })
hi('@keyword.type',        { fg = '#E879F9', fmt = 'bold' })
hi('@keyword.modifier',    { fg = '#D946EF', fmt = 'bold' })
hi('@keyword.repeat',      { fg = '#C084FC', fmt = 'bold' })
hi('@keyword.conditional', { fg = '#C084FC', fmt = 'bold' })
hi('@keyword.conditional.ternary', { fg = '#70D7FF' })
hi('@keyword.exception',   { fg = '#FF2E4C', fmt = 'bold' })
hi('@keyword.directive',   { fg = '#FF4D6D', fmt = 'bold' })
hi('@keyword.directive.define', { fg = '#FF4D6D', fmt = 'bold' })
hi('@keyword.debug',       { fg = '#D946EF', fmt = 'bold' })
hi('@keyword.return',      { fg = '#FF2E4C', fmt = 'bold' })
hi('@comment',             { fg = '#61708A', fmt = 'italic' })
hi('@comment.documentation', { fg = '#61708A', fmt = 'italic' })
hi('@comment.error',       { fg = '#FF2E4C', fmt = 'bold,italic' })
hi('@comment.warning',     { fg = '#FFD166', fmt = 'bold,italic' })
hi('@comment.todo',        { fg = '#000000', bg = '#FFD166', fmt = 'bold' })
hi('@comment.note',        { fg = '#38BDF8', fmt = 'bold,italic' })
hi('@operator',            { fg = '#70D7FF' })
hi('@punctuation',         { fg = '#94A3B8' })
hi('@punctuation.delimiter', { fg = '#94A3B8' })
hi('@punctuation.bracket',   { fg = '#94A3B8' })
hi('@punctuation.special',   { fg = '#70D7FF' })
hi('@attribute',           { fg = '#C084FC' })
hi('@module',              { fg = '#FACC15' })
hi('@module.builtin',      { fg = '#FF4D6D' })
hi('@label',               { fg = '#FFD166', fmt = 'bold' })

-- ── Python ─────────────────────────────────────────────────────────────
hi('@variable.python',              { fg = '#E2E8F0' })
hi('@variable.parameter.python',    { fg = '#FF9E64' })
hi('@variable.member.python',       { fg = '#C084FC' })
hi('@variable.builtin.python',      { fg = '#FF4D6D' })
hi('@function.python',              { fg = '#38BDF8' })
hi('@function.call.python',         { fg = '#38BDF8' })
hi('@function.method.python',       { fg = '#22D3EE' })
hi('@function.method.call.python',  { fg = '#22D3EE' })
hi('@function.builtin.python',      { fg = '#FF4D6D' })
hi('@type.python',                  { fg = '#FFD166' })
hi('@type.builtin.python',          { fg = '#FBBF24', fmt = 'bold' })
hi('@constructor.python',           { fg = '#FFD166', fmt = 'bold' })
hi('@string.python',                { fg = '#4ADE80' })
hi('@string.documentation.python',  { fg = '#61708A', fmt = 'italic' })
hi('@number.python',                { fg = '#FF9E64' })
hi('@boolean.python',               { fg = '#FF9E64', fmt = 'bold' })
hi('@constant.builtin.python',      { fg = '#FACC15', fmt = 'bold' })
hi('@keyword.python',               { fg = '#D946EF', fmt = 'bold' })
hi('@keyword.function.python',      { fg = '#D946EF', fmt = 'bold' })
hi('@keyword.import.python',        { fg = '#E879F9', fmt = 'bold' })
hi('@keyword.conditional.python',   { fg = '#C084FC', fmt = 'bold' })
hi('@keyword.repeat.python',        { fg = '#C084FC', fmt = 'bold' })
hi('@keyword.coroutine.python',     { fg = '#D946EF', fmt = 'bold' })
hi('@keyword.exception.python',     { fg = '#FF2E4C', fmt = 'bold' })
hi('@keyword.operator.python',      { fg = '#D946EF', fmt = 'bold' })
hi('@keyword.type.python',          { fg = '#E879F9', fmt = 'bold' })
hi('@keyword.debug.python',         { fg = '#D946EF', fmt = 'bold' })
hi('@keyword.return.python',        { fg = '#FF2E4C', fmt = 'bold' })
hi('@operator.python',              { fg = '#70D7FF' })
hi('@punctuation.python',           { fg = '#94A3B8' })
hi('@punctuation.special.python',   { fg = '#70D7FF' })
hi('@module.python',                { fg = '#FACC15' })
hi('@attribute.python',             { fg = '#C084FC' })

-- ── Lua ────────────────────────────────────────────────────────────────
hi('@variable.lua',              { fg = '#E2E8F0' })
hi('@variable.parameter.lua',    { fg = '#FF9E64' })
hi('@variable.member.lua',       { fg = '#C084FC' })
hi('@variable.builtin.lua',      { fg = '#FF4D6D' })
hi('@function.lua',              { fg = '#38BDF8' })
hi('@function.call.lua',         { fg = '#38BDF8' })
hi('@function.method.lua',       { fg = '#22D3EE' })
hi('@function.method.call.lua',  { fg = '#22D3EE' })
hi('@function.builtin.lua',      { fg = '#FF4D6D' })
hi('@type.lua',                  { fg = '#FFD166' })
hi('@type.builtin.lua',          { fg = '#FBBF24', fmt = 'bold' })
hi('@constructor.lua',           { fg = '#FFD166', fmt = 'bold' })
hi('@string.lua',                { fg = '#4ADE80' })
hi('@number.lua',                { fg = '#FF9E64' })
hi('@boolean.lua',               { fg = '#FF9E64', fmt = 'bold' })
hi('@keyword.lua',               { fg = '#D946EF', fmt = 'bold' })
hi('@keyword.function.lua',      { fg = '#D946EF', fmt = 'bold' })
hi('@keyword.conditional.lua',   { fg = '#C084FC', fmt = 'bold' })
hi('@keyword.repeat.lua',        { fg = '#C084FC', fmt = 'bold' })
hi('@keyword.operator.lua',      { fg = '#D946EF', fmt = 'bold' })
hi('@keyword.return.lua',        { fg = '#FF2E4C', fmt = 'bold' })
hi('@operator.lua',              { fg = '#70D7FF' })
hi('@punctuation.lua',           { fg = '#94A3B8' })
hi('@module.lua',                { fg = '#FACC15' })
hi('@property.lua',              { fg = '#C084FC' })

-- ── C ──────────────────────────────────────────────────────────────────
hi('@variable.c',              { fg = '#E2E8F0' })
hi('@variable.parameter.c',    { fg = '#FF9E64' })
hi('@variable.member.c',       { fg = '#C084FC' })
hi('@variable.builtin.c',      { fg = '#FF4D6D' })
hi('@function.c',              { fg = '#38BDF8' })
hi('@function.call.c',         { fg = '#38BDF8' })
hi('@function.builtin.c',      { fg = '#FF4D6D' })
hi('@function.macro.c',        { fg = '#FF4D6D' })
hi('@type.c',                  { fg = '#FFD166' })
hi('@type.builtin.c',          { fg = '#FBBF24', fmt = 'bold' })
hi('@type.qualifier.c',        { fg = '#D946EF', fmt = 'bold' })
hi('@string.c',                { fg = '#4ADE80' })
hi('@number.c',                { fg = '#FF9E64' })
hi('@boolean.c',               { fg = '#FF9E64', fmt = 'bold' })
hi('@constant.c',              { fg = '#FACC15' })
hi('@constant.builtin.c',      { fg = '#FACC15', fmt = 'bold' })
hi('@keyword.c',               { fg = '#D946EF', fmt = 'bold' })
hi('@keyword.type.c',          { fg = '#E879F9', fmt = 'bold' })
hi('@keyword.directive.c',     { fg = '#FF4D6D', fmt = 'bold' })
hi('@keyword.directive.define.c', { fg = '#FF4D6D', fmt = 'bold' })
hi('@keyword.conditional.c',   { fg = '#C084FC', fmt = 'bold' })
hi('@keyword.repeat.c',        { fg = '#C084FC', fmt = 'bold' })
hi('@keyword.return.c',        { fg = '#FF2E4C', fmt = 'bold' })
hi('@operator.c',              { fg = '#70D7FF' })
hi('@punctuation.c',           { fg = '#94A3B8' })

-- ── C++ ────────────────────────────────────────────────────────────────
hi('@variable.cpp',              { fg = '#E2E8F0' })
hi('@variable.parameter.cpp',    { fg = '#FF9E64' })
hi('@variable.member.cpp',       { fg = '#C084FC' })
hi('@variable.builtin.cpp',      { fg = '#FF4D6D' })
hi('@function.cpp',              { fg = '#38BDF8' })
hi('@function.call.cpp',         { fg = '#38BDF8' })
hi('@function.method.cpp',       { fg = '#22D3EE' })
hi('@function.method.call.cpp',  { fg = '#22D3EE' })
hi('@function.builtin.cpp',      { fg = '#FF4D6D' })
hi('@constructor.cpp',           { fg = '#FFD166', fmt = 'bold' })
hi('@type.cpp',                  { fg = '#FFD166' })
hi('@type.builtin.cpp',          { fg = '#FBBF24', fmt = 'bold' })
hi('@type.qualifier.cpp',        { fg = '#D946EF', fmt = 'bold' })
hi('@string.cpp',                { fg = '#4ADE80' })
hi('@number.cpp',                { fg = '#FF9E64' })
hi('@boolean.cpp',               { fg = '#FF9E64', fmt = 'bold' })
hi('@constant.cpp',              { fg = '#FACC15' })
hi('@constant.builtin.cpp',      { fg = '#FACC15', fmt = 'bold' })
hi('@keyword.cpp',               { fg = '#D946EF', fmt = 'bold' })
hi('@keyword.type.cpp',          { fg = '#E879F9', fmt = 'bold' })
hi('@keyword.directive.cpp',     { fg = '#FF4D6D', fmt = 'bold' })
hi('@keyword.conditional.cpp',   { fg = '#C084FC', fmt = 'bold' })
hi('@keyword.repeat.cpp',        { fg = '#C084FC', fmt = 'bold' })
hi('@keyword.return.cpp',        { fg = '#FF2E4C', fmt = 'bold' })
hi('@keyword.exception.cpp',     { fg = '#FF2E4C', fmt = 'bold' })
hi('@operator.cpp',              { fg = '#70D7FF' })
hi('@punctuation.cpp',           { fg = '#94A3B8' })

-- ── LSP Semantic Tokens ────────────────────────────────────────────────
hi('@lsp.type.variable',      { fg = '#E2E8F0' })
hi('@lsp.type.parameter',     { fg = '#FF9E64' })
hi('@lsp.type.property',      { fg = '#C084FC' })
hi('@lsp.type.function',      { fg = '#38BDF8' })
hi('@lsp.type.method',        { fg = '#22D3EE' })
hi('@lsp.type.class',         { fg = '#FFD166', fmt = 'bold' })
hi('@lsp.type.type',          { fg = '#FFD166' })
hi('@lsp.type.struct',        { fg = '#FFD166' })
hi('@lsp.type.interface',     { fg = '#FFD166' })
hi('@lsp.type.enum',          { fg = '#FFD166' })
hi('@lsp.type.enumMember',    { fg = '#F59E0B' })
hi('@lsp.type.macro',         { fg = '#FF4D6D' })
hi('@lsp.type.namespace',     { fg = '#FACC15' })
hi('@lsp.type.string',        { fg = '#4ADE80' })
hi('@lsp.type.number',        { fg = '#FF9E64' })
hi('@lsp.type.keyword',       { fg = '#D946EF', fmt = 'bold' })
hi('@lsp.type.comment',       { fg = '#61708A', fmt = 'italic' })
hi('@lsp.type.decorator',     { fg = '#C084FC' })
hi('@lsp.typemod.variable.defaultLibrary',  { fg = '#FF4D6D' })
hi('@lsp.typemod.function.defaultLibrary',  { fg = '#FF4D6D' })
hi('@lsp.typemod.method.defaultLibrary',    { fg = '#22D3EE' })
hi('@lsp.typemod.class.defaultLibrary',     { fg = '#FFD166' })
hi('@lsp.typemod.type.defaultLibrary',      { fg = '#FFD166' })
hi('@lsp.typemod.keyword.async',            { fg = '#D946EF', fmt = 'bold' })
hi('@lsp.typemod.function.declaration',     { fg = '#38BDF8' })
hi('@lsp.typemod.method.declaration',       { fg = '#22D3EE' })
-- Language-specific LSP (Python / C / C++)
hi('@lsp.type.variable.python',  { fg = '#E2E8F0' })
hi('@lsp.type.parameter.python', { fg = '#FF9E64' })
hi('@lsp.type.property.python',  { fg = '#C084FC' })
hi('@lsp.type.function.python',  { fg = '#38BDF8' })
hi('@lsp.type.method.python',    { fg = '#22D3EE' })
hi('@lsp.type.class.python',     { fg = '#FFD166', fmt = 'bold' })
hi('@lsp.type.type.python',      { fg = '#FFD166' })
hi('@lsp.type.namespace.python', { fg = '#FACC15' })
hi('@lsp.type.decorator.python', { fg = '#C084FC' })
hi('@lsp.typemod.variable.defaultLibrary.python', { fg = '#FF4D6D' })
hi('@lsp.typemod.class.defaultLibrary.python',    { fg = '#FFD166' })
hi('@lsp.type.variable.c',    { fg = '#E2E8F0' })
hi('@lsp.type.variable.cpp',  { fg = '#E2E8F0' })
hi('@lsp.type.parameter.c',   { fg = '#FF9E64' })
hi('@lsp.type.parameter.cpp', { fg = '#FF9E64' })
hi('@lsp.type.property.c',    { fg = '#C084FC' })
hi('@lsp.type.property.cpp',  { fg = '#C084FC' })
hi('@lsp.type.function.c',    { fg = '#38BDF8' })
hi('@lsp.type.function.cpp',  { fg = '#38BDF8' })
hi('@lsp.type.method.cpp',    { fg = '#22D3EE' })
hi('@lsp.type.class.cpp',     { fg = '#FFD166', fmt = 'bold' })
hi('@lsp.type.type.c',        { fg = '#FFD166' })
hi('@lsp.type.type.cpp',      { fg = '#FFD166' })
hi('@lsp.type.enum.c',        { fg = '#FFD166' })
hi('@lsp.type.enum.cpp',      { fg = '#FFD166' })
hi('@lsp.type.enumMember.c',  { fg = '#F59E0B' })
hi('@lsp.type.enumMember.cpp', { fg = '#F59E0B' })
hi('@lsp.type.macro.c',       { fg = '#FF4D6D' })
hi('@lsp.type.macro.cpp',     { fg = '#FF4D6D' })
hi('@lsp.type.namespace.cpp', { fg = '#FACC15' })

-- ── Markdown & Documentation ───────────────────────────────────────────
hi('@markup.heading',          { fg = '#69AFFF', fmt = 'bold' })
hi('@markup.heading.1',        { fg = '#69AFFF', fmt = 'bold' })
hi('@markup.heading.2',        { fg = '#C7A6FF', fmt = 'bold' })
hi('@markup.heading.3',        { fg = '#7FE3C2', fmt = 'bold' })
hi('@markup.heading.4',        { fg = '#70D7FF', fmt = 'bold' })
hi('@markup.heading.5',        { fg = '#FF9E64', fmt = 'bold' })
hi('@markup.heading.6',        { fg = '#A9B9D6', fmt = 'bold' })
hi('@markup.heading.1.marker', { fg = '#53627A', fmt = 'bold' })
hi('@markup.heading.2.marker', { fg = '#53627A', fmt = 'bold' })
hi('@markup.heading.3.marker', { fg = '#53627A', fmt = 'bold' })
hi('@markup.heading.4.marker', { fg = '#53627A', fmt = 'bold' })
hi('@markup.heading.5.marker', { fg = '#53627A', fmt = 'bold' })
hi('@markup.heading.6.marker', { fg = '#53627A', fmt = 'bold' })
hi('@markup.strong',          { fg = '#D7E3FF', fmt = 'bold' })
hi('@markup.italic',          { fg = '#D7E3FF', fmt = 'italic' })
hi('@markup.strikethrough',   { fg = '#53627A', fmt = 'strikethrough' })
hi('@markup.raw',             { fg = '#B8E986' })
hi('@markup.raw.inline',      { fg = '#B8E986', bg = '#141414' })
hi('@markup.raw.block',       { fg = '#D7E3FF' })
hi('@markup.link',            { fg = '#69AFFF' })
hi('@markup.link.label',      { fg = '#69AFFF' })
hi('@markup.link.url',        { fg = '#70D7FF', fmt = 'underline' })
hi('@markup.list',            { fg = '#70D7FF' })
hi('@markup.list.checked',    { fg = '#7FE3C2' })
hi('@markup.list.unchecked',  { fg = '#53627A' })
hi('@markup.quote',           { fg = '#61708A', fmt = 'italic' })
hi('@markup.math',            { fg = '#FF9E64' })

-- Vim native markdown groups
hi('markdownH1',          { fg = '#69AFFF', fmt = 'bold' })
hi('markdownH2',          { fg = '#C7A6FF', fmt = 'bold' })
hi('markdownH3',          { fg = '#7FE3C2', fmt = 'bold' })
hi('markdownH4',          { fg = '#70D7FF', fmt = 'bold' })
hi('markdownH5',          { fg = '#FF9E64', fmt = 'bold' })
hi('markdownH6',          { fg = '#A9B9D6', fmt = 'bold' })
hi('markdownBold',        { fg = '#D7E3FF', fmt = 'bold' })
hi('markdownItalic',      { fg = '#D7E3FF', fmt = 'italic' })
hi('markdownCode',        { fg = '#B8E986' })
hi('markdownCodeBlock',   { fg = '#D7E3FF' })
hi('markdownLinkText',    { fg = '#69AFFF' })
hi('markdownUrl',         { fg = '#70D7FF', fmt = 'underline' })
hi('markdownRule',        { fg = '#354357', fmt = 'bold' })
hi('markdownBlockquote',  { fg = '#61708A', fmt = 'italic' })
hi('markdownListMarker',  { fg = '#70D7FF' })

-- Render-Markdown plugin
hi('RenderMarkdownH1',          { fg = '#69AFFF', fmt = 'bold' })
hi('RenderMarkdownH2',          { fg = '#C7A6FF', fmt = 'bold' })
hi('RenderMarkdownH3',          { fg = '#7FE3C2', fmt = 'bold' })
hi('RenderMarkdownH4',          { fg = '#70D7FF', fmt = 'bold' })
hi('RenderMarkdownH5',          { fg = '#FF9E64', fmt = 'bold' })
hi('RenderMarkdownH6',          { fg = '#A9B9D6', fmt = 'bold' })
hi('RenderMarkdownH1Bg',        { bg = '#10151C' })
hi('RenderMarkdownH2Bg',        { bg = '#0E141D' })
hi('RenderMarkdownH3Bg',        { bg = '#0A0F16' })
hi('RenderMarkdownH4Bg',        { bg = '#070B10' })
hi('RenderMarkdownH5Bg',        {})
hi('RenderMarkdownH6Bg',        {})
hi('RenderMarkdownCode',        { bg = '#0A0A0A' })
hi('RenderMarkdownCodeInline',  { bg = '#141414', fg = '#B8E986' })
hi('RenderMarkdownBullet',      { fg = '#70D7FF' })
hi('RenderMarkdownTableHead',   { fg = '#69AFFF', fmt = 'bold' })
hi('RenderMarkdownTableRow',    { fg = '#354357' })
hi('RenderMarkdownTableFill',   { fg = '#1E2836' })
hi('RenderMarkdownQuote',       { fg = '#61708A', fmt = 'italic' })
hi('RenderMarkdownLink',        { fg = '#69AFFF' })
hi('RenderMarkdownWikiLink',    { fg = '#70D7FF' })
hi('RenderMarkdownTodo',        { fg = '#FF9E64' })
hi('RenderMarkdownChecked',     { fg = '#7FE3C2' })
hi('RenderMarkdownUnchecked',   { fg = '#53627A' })

-- ── Diagnostics ────────────────────────────────────────────────────────
hi('DiagnosticError',          { fg = '#FF8FA3' })
hi('DiagnosticWarn',           { fg = '#FFD166' })
hi('DiagnosticInfo',           { fg = '#70D7FF' })
hi('DiagnosticHint',           { fg = '#7FE3C2' })
hi('DiagnosticUnderlineError', { sp = '#FF8FA3', fmt = 'undercurl' })
hi('DiagnosticUnderlineWarn',  { sp = '#FFD166', fmt = 'undercurl' })
hi('DiagnosticUnderlineInfo',  { sp = '#70D7FF', fmt = 'undercurl' })
hi('DiagnosticUnderlineHint',  { sp = '#7FE3C2', fmt = 'undercurl' })
hi('DiagnosticUnderlineOk',    { sp = '#B8E986', fmt = 'undercurl' })
hi('LspSignatureActiveParameter', { fg = '#FFFFFF', bg = '#4A0E17', fmt = 'bold,underline' })

-- ── Git & Diffs ────────────────────────────────────────────────────────
hi('GitSignsAdd',       { fg = '#7FE3C2' })
hi('GitSignsChange',    { fg = '#FFD166' })
hi('GitSignsDelete',    { fg = '#FF8FA3' })
hi('GitSignsAddNr',     { fg = '#7FE3C2' })
hi('GitSignsChangeNr',  { fg = '#FFD166' })
hi('GitSignsDeleteNr',  { fg = '#FF8FA3' })
hi('DiffAdd',           { bg = '#0A241A', fg = '#7FE3C2' })
hi('DiffChange',        { bg = '#261C08', fg = '#FFD166' })
hi('DiffDelete',        { bg = '#2B0E18', fg = '#FF8FA3' })
hi('DiffText',          { bg = '#4A3610', fg = '#FFE29A', fmt = 'bold' })

-- ── Search & Selection ─────────────────────────────────────────────────
hi('Search',    { bg = '#2D234D', fg = '#E9D7FF' })
hi('IncSearch', { bg = '#F7768E', fg = '#000000', fmt = 'bold' })
hi('CurSearch', { bg = '#FF9E64', fg = '#000000', fmt = 'bold' })
hi('Visual',    { bg = '#24204A', fg = p.fg })
hi('VisualNOS', { bg = '#24204A', fg = p.fg })

-- ── Spellcheck ─────────────────────────────────────────────────────────
hi('SpellBad',   { sp = p.red,    fmt = 'undercurl' })
hi('SpellCap',   { sp = p.yellow, fmt = 'undercurl' })
hi('SpellRare',  { sp = p.cyan,   fmt = 'undercurl' })
hi('SpellLocal', { sp = p.green,  fmt = 'undercurl' })
hi('Todo',       { bg = p.yellow, fg = p.bg0, fmt = 'bold' })

-- ── Float & Context ────────────────────────────────────────────────────
hi('FloatShadow',        { bg = p.bg0 })
hi('FloatShadowThrough', { bg = p.bg0 })

-- ── Snacks & UI Plugin Chrome ──────────────────────────────────────────
groups('SnacksDashboardFile',    { fg = '#FFFFFF' })
groups('SnacksDashboardDesc',    { fg = '#D7E3FF' })
groups('SnacksDashboardIcon',    { fg = '#FF4D6D' })
groups('SnacksDashboardFooter',  { fg = '#A8606B' })
groups('SnacksDashboardHeader',  { fg = '#FF2E4C', fmt = 'bold' })
groups('SnacksDashboardKey',     { fg = '#FF4D6D', fmt = 'bold' })
groups('SnacksDashboardSpecial', { fg = '#FF2E4C', fmt = 'bold' })
groups('SnacksDashboardDir',     { fg = '#A8606B' })
groups('WhichKey',      { fg = '#FF4D6D' })
groups('WhichKeyGroup', { fg = '#FF2E4C' })
groups('WhichKeyDesc',  { fg = p.fg })
groups('NoiceCmdlineIcon', { fg = '#FF2E4C' })
groups('SnacksIndent',      { fg = '#2A0E15' })
groups('SnacksIndentScope', { fg = '#FF2E4C' })
groups('BufferLineFill',            { bg = '#0A0A0E' })
groups('BufferLineBackground',      { bg = '#0A0A0E', fg = '#7A5A62' })
groups('BufferLineBufferSelected',  { bg = '#3D0D14', fg = '#FFFFFF', fmt = 'bold' })
groups('BufferLineIndicatorSelected', { bg = '#3D0D14', fg = '#FF2E4C' })

-- ── Surface highlights (panels, popups, completion) ────────────────────
-- Applied last so they win over any earlier definitions.
local ok, surfaces = pcall(require, 'config.surfaces')
if ok then
  for name, spec in pairs(surfaces.highlights()) do
    hi(name, spec)
  end
end
