add_newline = true
format = "$directory$git_branch$git_status$python$c$nodejs$cmd_duration$line_break$character"
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
[directory]
style = "bold white"
truncation_length = 3
truncate_to_repo = true
[git_branch]
symbol = " "
style = "#aaaaaa"
[git_status]
style = "#d6bf8f"
[python]
symbol = " "
style = "#91b4d5"
format = "[${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"
[c]
symbol = " "
style = "#91b4d5"
[cmd_duration]
min_time = 2000
style = "#888888"
