return {
  {
    "navarasu/onedark.nvim",
    lazy = false,
    priority = 1000,
    opts = {
      code_style = { comments = "italic", keywords = "none", functions = "none", strings = "none", variables = "none" },
      -- Pure black canvas; opaque filled surfaces and one selection accent.
      colors = {
        bg0 = "#000000", bg_d = "#0A0A0A", bg1 = "#141414",
        bg2 = "#1E1E1E", bg3 = "#2A2A2A",
        fg = "#E6E6E6", grey = "#7A7A7A", light_grey = "#A0A0A0",
        blue = "#7FB4F5", green = "#93D68F", purple = "#82AAFF",
        red = "#E88B8B", yellow = "#E8D48B", cyan = "#7FD4C4",
      },
      highlights = {
        NoiceCmdlinePopupTitleCmdline = { fg = "#82AAFF", bg = "#121923", fmt = "bold" },
        NoiceCmdlinePopupTitleLua = { fg = "#82AAFF", bg = "#121923", fmt = "bold" },
        NoiceCmdlinePopupTitleSearch = { fg = "#82AAFF", bg = "#121923", fmt = "bold" },
        NoiceCmdlinePopupTitleHelp = { fg = "#82AAFF", bg = "#121923", fmt = "bold" },
        NoiceCmdlinePopupTitleFilter = { fg = "#82AAFF", bg = "#121923", fmt = "bold" },
        NoiceCmdlinePopupTitleCalculator = { fg = "#82AAFF", bg = "#121923", fmt = "bold" },
        NoiceCmdlinePopupTitleInput = { fg = "#82AAFF", bg = "#121923", fmt = "bold" },

        BlackDocsTitle = { fg = "#82AAFF", bg = "#10151C", fmt = "bold" },
        BlackDocsHint = { fg = "#A0AFC1", bg = "#10151C" },
        CmpItemAbbr = { fg = "$fg" },
        CmpItemKind = { fg = "#82AAFF" },
        ["@lsp.typemod.variable.defaultLibrary.python"] = { fg = "#C4A7E7" },
        ["@lsp.typemod.class.defaultLibrary.python"] = { fg = "#78DCCA" },
        ["@lsp.type.namespace.python"] = { fg = "#B8D7F0" },
        ["@lsp.type.decorator.python"] = { fg = "#C4A7E7" },

        BlackBrand = { fg = "$fg", fmt = "bold" },
        BlackLabel = { fg = "$purple", fmt = "bold" },
        BlackMuted = { fg = "$light_grey" },
        BlackKey = { fg = "$purple", bg = "#162439", fmt = "bold" },
        -- Python: identifiers stay readable; structure and values have distinct roles.
        ["@variable.python"] = { fg = "#B8D7F0" },
        ["@variable.parameter.python"] = { fg = "#B8D7F0" },
        ["@variable.member.python"] = { fg = "#CCD6E0" },
        ["@variable.builtin.python"] = { fg = "#C4A7E7" },
        ["@keyword.import.python"] = { fg = "#C4A7E7" },
        ["@keyword.function.python"] = { fg = "#C4A7E7" },
        ["@keyword.conditional.python"] = { fg = "#C4A7E7" },
        ["@keyword.repeat.python"] = { fg = "#C4A7E7" },
        ["@keyword.return.python"] = { fg = "#C4A7E7" },
        ["@keyword.exception.python"] = { fg = "#C4A7E7" },
        ["@keyword.operator.python"] = { fg = "#C4A7E7" },
        ["@keyword.type.python"] = { fg = "#C4A7E7" },
        ["@keyword.coroutine.python"] = { fg = "#C4A7E7" },
        ["@keyword.debug.python"] = { fg = "#C4A7E7" },
        ["@constructor.python"] = { fg = "#78DCCA" },
        ["@punctuation.special.python"] = { fg = "$light_grey" },
        ["@keyword.python"] = { fg = "#C4A7E7" },
        ["@function.python"] = { fg = "#E5C07B" },
        ["@function.call.python"] = { fg = "#E5C07B" },
        ["@function.method.python"] = { fg = "#E5C07B" },
        ["@function.method.call.python"] = { fg = "#E5C07B" },
        ["@function.builtin.python"] = { fg = "#E5C07B" },
        ["@type.builtin.python"] = { fg = "#78DCCA" },
        ["@string.documentation.python"] = { fg = "$light_grey", fmt = "italic" },
        ["@module.python"] = { fg = "#B8D7F0" },
        ["@attribute.python"] = { fg = "#C4A7E7" },
        ["@constant.builtin.python"] = { fg = "#D9A98F" },
        ["@type.python"] = { fg = "#78DCCA" },
        ["@string.python"] = { fg = "#B5CEA8" },
        ["@number.python"] = { fg = "#D9A98F" },
        ["@boolean.python"] = { fg = "#D9A98F" },
        ["@operator.python"] = { fg = "$light_grey" },
        ["@punctuation.python"] = { fg = "$light_grey" },
        ["@lsp.type.variable.python"] = { fg = "#B8D7F0" },
        ["@lsp.type.parameter.python"] = { fg = "#B8D7F0" },
        ["@lsp.type.property.python"] = { fg = "#CCD6E0" },
        ["@lsp.type.function.python"] = { fg = "#E5C07B" },
        ["@lsp.type.method.python"] = { fg = "#E5C07B" },
        ["@lsp.type.class.python"] = { fg = "#78DCCA" },
        ["@lsp.type.type.python"] = { fg = "#78DCCA" },
        BlackDocs = { bg = "#10151C", fg = "$fg" },
        BlackDocsBorder = { bg = "#10151C", fg = "#354357" },
        NoiceCmdlineIcon = { fg = "$purple" },
        NoiceCmdlinePopupTitle = { fg = "$purple", bg = "#121923", fmt = "bold" },
        Comment = { fg = "$grey", fmt = "italic" },
        ["@comment"] = { fg = "$grey", fmt = "italic" },
        RenderMarkdownH1Bg = { bg = "$bg2" },
        RenderMarkdownH2Bg = { bg = "$bg1" },
        RenderMarkdownH3Bg = { bg = "$bg1" },
        RenderMarkdownCode = { bg = "$bg_d" },
        RenderMarkdownCodeInline = { bg = "$bg2", fg = "$fg" },
        RenderMarkdownTableHead = { fg = "$blue" },
        RenderMarkdownTableRow = { fg = "$bg3" },
        SnacksNotifierBorderTrace = { bg = "$bg1", fg = "$bg3" },
        SnacksNotifierTrace = { bg = "$bg1", fg = "$fg" },
        SnacksNotifierBorderDebug = { bg = "$bg1", fg = "$bg3" },
        SnacksNotifierDebug = { bg = "$bg1", fg = "$fg" },
        SnacksNotifierBorderError = { bg = "$bg1", fg = "$bg3" },
        SnacksNotifierError = { bg = "$bg1", fg = "$fg" },
        SnacksNotifierBorderWarn = { bg = "$bg1", fg = "$bg3" },
        SnacksNotifierWarn = { bg = "$bg1", fg = "$fg" },
        SnacksNotifierBorderInfo = { bg = "$bg1", fg = "$bg3" },
        SnacksNotifierInfo = { bg = "$bg1", fg = "$fg" },
        SnacksInputNormal = { bg = "$bg1", fg = "$fg" },
        SnacksInputBorder = { bg = "$bg1", fg = "$bg3" },
        SnacksInputTitle = { bg = "$bg1", fg = "$blue", fmt = "bold" },
        SnacksNotifierHistory = { bg = "$bg1", fg = "$fg" },
        NoicePopup = { bg = "$bg1", fg = "$fg" },
        NoicePopupBorder = { bg = "$bg1", fg = "$bg3" },
        SnacksPickerBox = { bg = "$bg2", fg = "$fg" },
        SnacksPickerBoxBorder = { bg = "$bg2", fg = "$bg2" },
        SnacksPickerBoxTitle = { bg = "$bg1", fg = "$blue", fmt = "bold" },
        NoiceCmdlinePopup = { bg = "#121923", fg = "$fg" },
        NoiceCmdlinePopupBorder = { bg = "#121923", fg = "#354357" },
        NoicePopupmenu = { bg = "$bg1", fg = "$fg" },
        NoicePopupmenuBorder = { bg = "$bg1", fg = "$bg3" },
        NoicePopupmenuSelected = { bg = "$bg2", fg = "$fg" },
        WhichKeyNormal = { bg = "$bg1", fg = "$fg" },
        WhichKeyBorder = { bg = "$bg1", fg = "$bg3" },
        LineNr = { fg = "$grey", bg = "NONE" },
        CursorLine = { bg = "$bg_d" },
        EndOfBuffer = { fg = "$bg0", bg = "NONE" },
        StatusLine = { bg = "$bg1", fg = "$fg" },
        StatusLineNC = { bg = "$bg_d", fg = "$grey" },
        NeoTreeDirectoryIcon = { fg = "$light_grey" },
        NeoTreeDirectoryName = { fg = "$light_grey" },
        NeoTreeRootName = { fg = "$fg", fmt = "bold" },
        NeoTreeIndentMarker = { fg = "#3D3D3D" },
        NeoTreeTabActive = { bg = "$bg2", fg = "$purple", fmt = "bold" },
        NeoTreeTabInactive = { bg = "$bg_d", fg = "$grey" },
        NeoTreeTabSeparatorActive = { bg = "$bg2", fg = "$bg3" },
        NeoTreeTabSeparatorInactive = { bg = "$bg_d", fg = "$bg3" },
        SnacksDashboardFile = { fg = "$fg" },
        SnacksDashboardDesc = { fg = "$fg" },
        SnacksDashboardIcon = { fg = "$light_grey" },
        SnacksDashboardFooter = { fg = "$grey" },
        WhichKey = { fg = "$blue" },
        WhichKeyGroup = { fg = "$blue" },
        WhichKeyDesc = { fg = "$fg" },
        NormalFloat = { bg = "$bg1", fg = "$fg" },
        FloatBorder = { bg = "$bg1", fg = "#1F1F1F" },
        FloatTitle = { bg = "$bg1", fg = "$fg", fmt = "bold" },
        WinSeparator = { fg = "$bg3", bg = "$bg0" },
        CursorLineNr = { fg = "$blue", fmt = "bold" },
        Pmenu = { bg = "$bg1", fg = "$fg" },
        PmenuSel = { bg = "#243B59", fg = "#FFFFFF", fmt = "bold" },
        CmpItemAbbrMatch = { fg = "$purple", fmt = "bold" },
        CmpItemAbbrMatchFuzzy = { fg = "$purple", fmt = "bold" },
        CmpItemMenu = { fg = "$light_grey" },
        BufferLineFill = { bg = "$bg1" },
        BufferLineBackground = { bg = "$bg1", fg = "$grey" },
        BufferLineBufferSelected = { bg = "$bg2", fg = "$fg", fmt = "bold" },
        BufferLineIndicatorSelected = { bg = "$bg2", fg = "$purple" },
        SnacksIndent = { fg = "#3D3D3D" },
        SnacksIndentScope = { fg = "$grey" },
        SnacksDashboardHeader = { fg = "$blue", fmt = "bold" },
        SnacksDashboardKey = { fg = "$purple", fmt = "bold" },
        NeoTreeNormal = { bg = "$bg1", fg = "$fg" },
        NeoTreeNormalNC = { bg = "$bg1", fg = "$fg" },
        NeoTreeCursorLine = { bg = "$bg2" },
        NeoTreeFileNameOpened = { fg = "$fg", fmt = "bold" },
        SnacksPickerInput = { bg = "$bg2", fg = "$fg" },
        SnacksPickerInputBorder = { bg = "$bg1", fg = "$bg3" },
        SnacksPickerInputTitle = { bg = "$bg1", fg = "$purple", fmt = "bold" },
        SnacksPickerInputFooter = { bg = "$bg1", fg = "$light_grey" },
        SnacksPickerPrompt = { fg = "$purple" },
        SnacksPickerList = { bg = "$bg2", fg = "$fg" },
        SnacksPickerListBorder = { bg = "$bg1", fg = "$bg3" },
        SnacksPickerListTitle = { bg = "$bg2", fg = "$fg", fmt = "bold" },
        SnacksPickerListCursorLine = { bg = "#162439", fg = "$fg", fmt = "bold" },
        SnacksPickerPreview = { bg = "$bg1", fg = "$fg" },
        SnacksPickerPreviewBorder = { bg = "$bg1", fg = "$bg1" },
        SnacksPickerPreviewTitle = { bg = "$bg1", fg = "$fg", fmt = "bold" },
        SnacksPickerMatch = { fg = "$purple", fmt = "bold" },
        SnacksPickerDir = { fg = "$light_grey" },
        SnacksPickerFile = { fg = "$fg", fmt = "bold" },
      },
    },
    config = function(_, opts)
      opts.highlights = vim.tbl_deep_extend("force", opts.highlights or {}, require("config.surfaces").highlights())
      require("onedark").setup(opts)
      require("onedark").load()
    end,
  },
  { "LazyVim/LazyVim", opts = { colorscheme = "onedark" } },
}
