return {
  {
    "navarasu/onedark.nvim",
    lazy = false,
    priority = 1000,
    opts = {
      code_style = { comments = "italic", keywords = "none", functions = "none", strings = "none", variables = "none" },
      diagnostics = {
        darker = false,
        undercurl = true,
        background = false,
      },
      -- Pure black canvas; opaque filled surfaces and one selection accent.
      colors = {
        bg0 = "#000000", bg_d = "#0A0A0A", bg1 = "#141414",
        bg2 = "#1E1E1E", bg3 = "#2A2A2A",
        fg = "#C8D3F5", grey = "#565F89", light_grey = "#A9B1D6",
        blue = "#82AAFF", green = "#C3E88D", purple = "#BB9AF7",
        red = "#F7768E", yellow = "#E0AF68", cyan = "#7DCFFF",
      },
      highlights = {
        CmpItemAbbr = { fg = "$fg" },
        CmpItemKind = { fg = "$cyan" },

        -- ── Shared semantic palette (TokyoNight/Zed-inspired on black) ─
        ["@variable"] = { fg = "#C8D3F5" },
        ["@variable.parameter"] = { fg = "#A9B1D6" },
        ["@variable.member"] = { fg = "#89DDFF" },
        ["@variable.builtin"] = { fg = "#F7768E" },
        ["@function"] = { fg = "#82AAFF" },
        ["@function.call"] = { fg = "#82AAFF" },
        ["@function.method"] = { fg = "#82AAFF" },
        ["@function.method.call"] = { fg = "#82AAFF" },
        ["@function.builtin"] = { fg = "#7DCFFF" },
        ["@type"] = { fg = "#86E1FC" },
        ["@type.builtin"] = { fg = "#86E1FC" },
        ["@constructor"] = { fg = "#73DACA" },
        ["@string"] = { fg = "#C3E88D" },
        ["@string.escape"] = { fg = "#FF9E64" },
        ["@character"] = { fg = "#C3E88D" },
        ["@number"] = { fg = "#FF9E64" },
        ["@boolean"] = { fg = "#FF9E64" },
        ["@constant"] = { fg = "#F7768E" },
        ["@constant.builtin"] = { fg = "#F7768E" },
        ["@keyword"] = { fg = "#BB9AF7", fmt = "bold" },
        ["@keyword.return"] = { fg = "#F7768E", fmt = "bold" },
        ["@operator"] = { fg = "#89DDFF" },
        ["@punctuation"] = { fg = "#A9B1D6" },
        ["@property"] = { fg = "#89DDFF" },
        ["@attribute"] = { fg = "#BB9AF7" },

        -- ── Custom surface groups ──────────────────────────────────────
        BlackBrand = { fg = "$fg", fmt = "bold" },
        BlackLabel = { fg = "$purple", fmt = "bold" },
        BlackMuted = { fg = "$light_grey" },
        BlackKey = { fg = "$purple", bg = "#162439", fmt = "bold" },

        -- ── Python: identifiers, structure, and values ─────────────────
        ["@variable.python"] = { fg = "#B8D7F0" },
        ["@variable.parameter.python"] = { fg = "#B8D7F0" },
        ["@variable.member.python"] = { fg = "#CCD6E0" },
        ["@variable.builtin.python"] = { fg = "#C4A7E7" },
        ["@keyword.import.python"] = { fg = "#C4A7E7" },
        ["@keyword.function.python"] = { fg = "#C4A7E7" },
        ["@keyword.conditional.python"] = { fg = "#C4A7E7" },
        ["@keyword.repeat.python"] = { fg = "#C4A7E7" },
        ["@keyword.return.python"] = { fg = "#C4A7E7" },
        ["@keyword.exception.python"] = { fg = "#C4A7E7" },
        ["@keyword.operator.python"] = { fg = "#C4A7E7" },
        ["@keyword.type.python"] = { fg = "#C4A7E7" },
        ["@keyword.coroutine.python"] = { fg = "#C4A7E7" },
        ["@keyword.debug.python"] = { fg = "#C4A7E7" },
        ["@keyword.python"] = { fg = "#C4A7E7" },
        ["@constructor.python"] = { fg = "#78DCCA" },
        ["@punctuation.special.python"] = { fg = "$light_grey" },
        ["@function.python"] = { fg = "#E5C07B" },
        ["@function.call.python"] = { fg = "#E5C07B" },
        ["@function.method.python"] = { fg = "#E5C07B" },
        ["@function.method.call.python"] = { fg = "#E5C07B" },
        ["@function.builtin.python"] = { fg = "#E5C07B" },
        ["@type.builtin.python"] = { fg = "#78DCCA" },
        ["@type.python"] = { fg = "#78DCCA" },
        ["@string.documentation.python"] = { fg = "$light_grey", fmt = "italic" },
        ["@string.python"] = { fg = "#B5CEA8" },
        ["@module.python"] = { fg = "#B8D7F0" },
        ["@attribute.python"] = { fg = "#C4A7E7" },
        ["@constant.builtin.python"] = { fg = "#D9A98F" },
        ["@number.python"] = { fg = "#D9A98F" },
        ["@boolean.python"] = { fg = "#D9A98F" },
        ["@operator.python"] = { fg = "$light_grey" },
        ["@punctuation.python"] = { fg = "$light_grey" },
        -- Python LSP token overrides
        ["@lsp.typemod.variable.defaultLibrary.python"] = { fg = "#C4A7E7" },
        ["@lsp.typemod.class.defaultLibrary.python"] = { fg = "#78DCCA" },
        ["@lsp.type.namespace.python"] = { fg = "#B8D7F0" },
        ["@lsp.type.decorator.python"] = { fg = "#C4A7E7" },
        ["@lsp.type.variable.python"] = { fg = "#B8D7F0" },
        ["@lsp.type.parameter.python"] = { fg = "#B8D7F0" },
        ["@lsp.type.property.python"] = { fg = "#CCD6E0" },
        ["@lsp.type.function.python"] = { fg = "#E5C07B" },
        ["@lsp.type.method.python"] = { fg = "#E5C07B" },
        ["@lsp.type.class.python"] = { fg = "#78DCCA" },
        ["@lsp.type.type.python"] = { fg = "#78DCCA" },

        -- ── Lua: consistent colors for editing your own config ─────────
        ["@variable.lua"] = { fg = "#B8D7F0" },
        ["@variable.builtin.lua"] = { fg = "#C4A7E7" },
        ["@keyword.lua"] = { fg = "#C4A7E7" },
        ["@keyword.function.lua"] = { fg = "#C4A7E7" },
        ["@keyword.return.lua"] = { fg = "#C4A7E7" },
        ["@keyword.repeat.lua"] = { fg = "#C4A7E7" },
        ["@keyword.conditional.lua"] = { fg = "#C4A7E7" },
        ["@keyword.operator.lua"] = { fg = "#C4A7E7" },
        ["@function.lua"] = { fg = "#E5C07B" },
        ["@function.call.lua"] = { fg = "#E5C07B" },
        ["@function.builtin.lua"] = { fg = "#E5C07B" },
        ["@function.method.lua"] = { fg = "#E5C07B" },
        ["@function.method.call.lua"] = { fg = "#E5C07B" },
        ["@constructor.lua"] = { fg = "#78DCCA" },
        ["@type.lua"] = { fg = "#78DCCA" },
        ["@type.builtin.lua"] = { fg = "#78DCCA" },
        ["@string.lua"] = { fg = "#B5CEA8" },
        ["@number.lua"] = { fg = "#D9A98F" },
        ["@boolean.lua"] = { fg = "#D9A98F" },
        ["@operator.lua"] = { fg = "$light_grey" },
        ["@punctuation.lua"] = { fg = "$light_grey" },
        ["@module.lua"] = { fg = "#B8D7F0" },

        -- ── C/C++: same palette for systems work ───────────────────────
        ["@variable.c"] = { fg = "#B8D7F0" },
        ["@variable.member.c"] = { fg = "#CCD6E0" },
        ["@keyword.c"] = { fg = "#C4A7E7" },
        ["@keyword.type.c"] = { fg = "#C4A7E7" },
        ["@keyword.directive.c"] = { fg = "#C4A7E7" },
        ["@keyword.conditional.c"] = { fg = "#C4A7E7" },
        ["@keyword.repeat.c"] = { fg = "#C4A7E7" },
        ["@keyword.return.c"] = { fg = "#C4A7E7" },
        ["@function.c"] = { fg = "#E5C07B" },
        ["@function.call.c"] = { fg = "#E5C07B" },
        ["@type.c"] = { fg = "#78DCCA" },
        ["@type.builtin.c"] = { fg = "#78DCCA" },
        ["@string.c"] = { fg = "#B5CEA8" },
        ["@number.c"] = { fg = "#D9A98F" },
        ["@operator.c"] = { fg = "$light_grey" },
        ["@punctuation.c"] = { fg = "$light_grey" },
        ["@constant.c"] = { fg = "#D9A98F" },
        -- C++ inherits C and adds its own
        ["@variable.cpp"] = { fg = "#B8D7F0" },
        ["@variable.member.cpp"] = { fg = "#CCD6E0" },
        ["@keyword.cpp"] = { fg = "#C4A7E7" },
        ["@keyword.type.cpp"] = { fg = "#C4A7E7" },
        ["@keyword.directive.cpp"] = { fg = "#C4A7E7" },
        ["@keyword.conditional.cpp"] = { fg = "#C4A7E7" },
        ["@keyword.repeat.cpp"] = { fg = "#C4A7E7" },
        ["@keyword.return.cpp"] = { fg = "#C4A7E7" },
        ["@function.cpp"] = { fg = "#E5C07B" },
        ["@function.call.cpp"] = { fg = "#E5C07B" },
        ["@function.method.cpp"] = { fg = "#E5C07B" },
        ["@function.method.call.cpp"] = { fg = "#E5C07B" },
        ["@type.cpp"] = { fg = "#78DCCA" },
        ["@type.builtin.cpp"] = { fg = "#78DCCA" },
        ["@string.cpp"] = { fg = "#B5CEA8" },
        ["@number.cpp"] = { fg = "#D9A98F" },
        ["@operator.cpp"] = { fg = "$light_grey" },
        ["@punctuation.cpp"] = { fg = "$light_grey" },
        ["@constant.cpp"] = { fg = "#D9A98F" },

        -- ── Language-specific semantic accents ────────────────────────
        -- These come after the legacy overrides above so every parser uses
        -- the same high-contrast role colors without losing language scope.
        ["@variable.python"] = { fg = "#C8D3F5" },
        ["@variable.parameter.python"] = { fg = "#A9B1D6" },
        ["@variable.member.python"] = { fg = "#89DDFF" },
        ["@function.python"] = { fg = "#82AAFF" },
        ["@function.call.python"] = { fg = "#82AAFF" },
        ["@function.method.python"] = { fg = "#82AAFF" },
        ["@function.method.call.python"] = { fg = "#82AAFF" },
        ["@function.builtin.python"] = { fg = "#7DCFFF" },
        ["@type.python"] = { fg = "#86E1FC" },
        ["@type.builtin.python"] = { fg = "#86E1FC" },
        ["@string.python"] = { fg = "#C3E88D" },
        ["@number.python"] = { fg = "#FF9E64" },
        ["@boolean.python"] = { fg = "#FF9E64" },
        ["@keyword.python"] = { fg = "#BB9AF7", fmt = "bold" },
        ["@keyword.return.python"] = { fg = "#F7768E", fmt = "bold" },
        ["@operator.python"] = { fg = "#89DDFF" },

        ["@variable.lua"] = { fg = "#C8D3F5" },
        ["@variable.builtin.lua"] = { fg = "#F7768E" },
        ["@function.lua"] = { fg = "#82AAFF" },
        ["@function.call.lua"] = { fg = "#82AAFF" },
        ["@function.method.lua"] = { fg = "#82AAFF" },
        ["@function.method.call.lua"] = { fg = "#82AAFF" },
        ["@function.builtin.lua"] = { fg = "#7DCFFF" },
        ["@type.lua"] = { fg = "#86E1FC" },
        ["@type.builtin.lua"] = { fg = "#86E1FC" },
        ["@string.lua"] = { fg = "#C3E88D" },
        ["@number.lua"] = { fg = "#FF9E64" },
        ["@boolean.lua"] = { fg = "#FF9E64" },
        ["@keyword.lua"] = { fg = "#BB9AF7", fmt = "bold" },
        ["@keyword.return.lua"] = { fg = "#F7768E", fmt = "bold" },
        ["@operator.lua"] = { fg = "#89DDFF" },

        ["@variable.c"] = { fg = "#C8D3F5" },
        ["@variable.member.c"] = { fg = "#89DDFF" },
        ["@function.c"] = { fg = "#82AAFF" },
        ["@function.call.c"] = { fg = "#82AAFF" },
        ["@type.c"] = { fg = "#86E1FC" },
        ["@type.builtin.c"] = { fg = "#86E1FC" },
        ["@string.c"] = { fg = "#C3E88D" },
        ["@number.c"] = { fg = "#FF9E64" },
        ["@constant.c"] = { fg = "#F7768E" },
        ["@keyword.c"] = { fg = "#BB9AF7", fmt = "bold" },
        ["@keyword.return.c"] = { fg = "#F7768E", fmt = "bold" },
        ["@operator.c"] = { fg = "#89DDFF" },

        ["@variable.cpp"] = { fg = "#C8D3F5" },
        ["@variable.member.cpp"] = { fg = "#89DDFF" },
        ["@function.cpp"] = { fg = "#82AAFF" },
        ["@function.call.cpp"] = { fg = "#82AAFF" },
        ["@function.method.cpp"] = { fg = "#82AAFF" },
        ["@function.method.call.cpp"] = { fg = "#82AAFF" },
        ["@type.cpp"] = { fg = "#86E1FC" },
        ["@type.builtin.cpp"] = { fg = "#86E1FC" },
        ["@string.cpp"] = { fg = "#C3E88D" },
        ["@number.cpp"] = { fg = "#FF9E64" },
        ["@constant.cpp"] = { fg = "#F7768E" },
        ["@keyword.cpp"] = { fg = "#BB9AF7", fmt = "bold" },
        ["@keyword.return.cpp"] = { fg = "#F7768E", fmt = "bold" },
        ["@operator.cpp"] = { fg = "#89DDFF" },

        -- Parser subcaptures and LSP semantic tokens must follow the same roles.
        ["@keyword.import.python"] = { fg = "#BB9AF7", fmt = "bold" },
        ["@keyword.function.python"] = { fg = "#BB9AF7", fmt = "bold" },
        ["@keyword.conditional.python"] = { fg = "#BB9AF7", fmt = "bold" },
        ["@keyword.repeat.python"] = { fg = "#BB9AF7", fmt = "bold" },
        ["@keyword.exception.python"] = { fg = "#F7768E", fmt = "bold" },
        ["@keyword.operator.python"] = { fg = "#89DDFF", fmt = "bold" },
        ["@keyword.type.python"] = { fg = "#86E1FC", fmt = "bold" },
        ["@keyword.coroutine.python"] = { fg = "#BB9AF7", fmt = "bold" },
        ["@keyword.debug.python"] = { fg = "#BB9AF7", fmt = "bold" },
        ["@keyword.function.lua"] = { fg = "#BB9AF7", fmt = "bold" },
        ["@keyword.return.lua"] = { fg = "#F7768E", fmt = "bold" },
        ["@keyword.repeat.lua"] = { fg = "#BB9AF7", fmt = "bold" },
        ["@keyword.conditional.lua"] = { fg = "#BB9AF7", fmt = "bold" },
        ["@keyword.operator.lua"] = { fg = "#89DDFF", fmt = "bold" },
        ["@keyword.type.c"] = { fg = "#86E1FC", fmt = "bold" },
        ["@keyword.directive.c"] = { fg = "#7DCFFF", fmt = "bold" },
        ["@keyword.conditional.c"] = { fg = "#BB9AF7", fmt = "bold" },
        ["@keyword.repeat.c"] = { fg = "#BB9AF7", fmt = "bold" },
        ["@keyword.type.cpp"] = { fg = "#86E1FC", fmt = "bold" },
        ["@keyword.directive.cpp"] = { fg = "#7DCFFF", fmt = "bold" },
        ["@keyword.conditional.cpp"] = { fg = "#BB9AF7", fmt = "bold" },
        ["@keyword.repeat.cpp"] = { fg = "#BB9AF7", fmt = "bold" },
        ["@lsp.type.variable.python"] = { fg = "#C8D3F5" },
        ["@lsp.type.parameter.python"] = { fg = "#A9B1D6" },
        ["@lsp.type.property.python"] = { fg = "#89DDFF" },
        ["@lsp.type.function.python"] = { fg = "#82AAFF" },
        ["@lsp.type.method.python"] = { fg = "#82AAFF" },
        ["@lsp.type.class.python"] = { fg = "#86E1FC" },
        ["@lsp.type.type.python"] = { fg = "#86E1FC" },
        ["@lsp.type.namespace.python"] = { fg = "#7DCFFF" },
        ["@lsp.type.decorator.python"] = { fg = "#BB9AF7" },
        ["@lsp.typemod.variable.defaultLibrary.python"] = { fg = "#7DCFFF" },
        ["@lsp.typemod.class.defaultLibrary.python"] = { fg = "#86E1FC" },

        -- ── Shared editor chrome ───────────────────────────────────────
        NoiceCmdlineIcon = { fg = "$purple" },
        Comment = { fg = "#8994A3", fmt = "italic" },
        ["@comment"] = { fg = "#8994A3", fmt = "italic" },
        RenderMarkdownH1Bg = { bg = "$bg2" },
        RenderMarkdownH2Bg = { bg = "$bg1" },
        RenderMarkdownH3Bg = { bg = "$bg1" },
        RenderMarkdownCode = { bg = "$bg_d" },
        RenderMarkdownCodeInline = { bg = "$bg2", fg = "$fg" },
        RenderMarkdownTableHead = { fg = "$blue" },
        RenderMarkdownTableRow = { fg = "$bg3" },
        LineNr = { fg = "#555555", bg = "NONE" },
        CursorLine = { bg = "#0E1520" },  -- Slightly clearer than previous #0D121A
        CursorLineNr = { fg = "#82AAFF", bg = "NONE", fmt = "bold" },
        MatchParen = { fg = "#82AAFF", bg = "#1E2836", fmt = "bold" },
        Folded = { fg = "#8994A3", bg = "#0A0F16", fmt = "italic" },
        FoldColumn = { fg = "#555555", bg = "NONE" },
        EndOfBuffer = { fg = "$bg0", bg = "NONE" },
        StatusLine = { bg = "$bg1", fg = "$fg" },
        StatusLineNC = { bg = "$bg_d", fg = "$grey" },
        SnacksDashboardFile = { fg = "$fg" },
        SnacksDashboardDesc = { fg = "$fg" },
        SnacksDashboardIcon = { fg = "$light_grey" },
        SnacksDashboardFooter = { fg = "$grey" },
        WhichKey = { fg = "$blue" },
        WhichKeyGroup = { fg = "$blue" },
        WhichKeyDesc = { fg = "$fg" },
        WinSeparator = { fg = "$bg3", bg = "$bg0" },
        Pmenu = { bg = "#10151C", fg = "$fg" },
        PmenuSel = { bg = "#243B59", fg = "#FFFFFF", fmt = "bold" },
        PmenuBorder = { fg = "#354357", bg = "#10151C" },
        PmenuSbar = { bg = "#10151C" },
        PmenuThumb = { bg = "#354357" },
        CmpItemAbbrMatch = { fg = "$purple", fmt = "bold" },
        CmpItemAbbrMatchFuzzy = { fg = "$purple", fmt = "bold" },
        CmpItemMenu = { fg = "$light_grey" },
        BufferLineFill = { bg = "$bg1" },
        BufferLineBackground = { bg = "$bg1", fg = "$grey" },
        BufferLineBufferSelected = { bg = "$bg2", fg = "$fg", fmt = "bold" },
        BufferLineIndicatorSelected = { bg = "$bg2", fg = "$purple" },
        SnacksIndent = { fg = "#28313E" },
        SnacksIndentScope = { fg = "#526D90" },
        SnacksDashboardHeader = { fg = "$blue", fmt = "bold" },
        SnacksDashboardKey = { fg = "$purple", fmt = "bold" },

        -- ── Git gutter: distinct add/change/delete ─────────────────────
        GitSignsAdd = { fg = "#73DACA" },
        GitSignsChange = { fg = "#E0AF68" },
        GitSignsDelete = { fg = "#F7768E" },
        GitSignsAddNr = { fg = "#73DACA" },
        GitSignsChangeNr = { fg = "#E0AF68" },
        GitSignsDeleteNr = { fg = "#F7768E" },
        DiffAdd = { bg = "#09261B", fg = "#C3E88D" },
        DiffChange = { bg = "#29200B", fg = "#E0AF68" },
        DiffDelete = { bg = "#2B0D18", fg = "#F7768E" },
        DiffText = { bg = "#4A3510", fg = "#FFCB6B", fmt = "bold" },

        -- ── Search and selection refinements ───────────────────────────
        Search = { bg = "#3B2E63", fg = "#E9D7FF", fmt = "bold" },
        IncSearch = { bg = "#F7768E", fg = "#160910", fmt = "bold" },
        CurSearch = { bg = "#FF9E64", fg = "#160D05", fmt = "bold" },
        Visual = { bg = "#24204A", fg = "$fg" },
        VisualNOS = { bg = "#24204A", fg = "$fg" },

        -- ── Diagnostics: elegant undercurls without distracting solid backgrounds ──
        DiagnosticUnderlineError = { sp = "$red", fmt = "undercurl", bg = "NONE" },
        DiagnosticUnderlineWarn = { sp = "$yellow", fmt = "undercurl", bg = "NONE" },
        DiagnosticUnderlineInfo = { sp = "$blue", fmt = "undercurl", bg = "NONE" },
        DiagnosticUnderlineHint = { sp = "$purple", fmt = "undercurl", bg = "NONE" },
        DiagnosticUnderlineOk = { sp = "$green", fmt = "undercurl", bg = "NONE" },

        -- ── Float shadows for depth ───────────────────────────────────
        FloatShadow = { bg = "#000000" },
        FloatShadowThrough = { bg = "#000000" },

        -- ── Treesitter context ─────────────────────────────────────────
        TreesitterContext = { bg = "#080C12" },
        TreesitterContextLineNumber = { fg = "#526D90" },
      },
    },
    config = function(_, opts)
      opts.highlights = vim.tbl_deep_extend("force", require("config.surfaces").highlights(), opts.highlights or {})
      require("onedark").setup(opts)
      require("onedark").load()
    end,
  },
}
