return {
  {
    "navarasu/onedark.nvim",
    lazy = false,
    priority = 1000,
    opts = {
      code_style = { comments = "italic", keywords = "bold", functions = "none", strings = "none", variables = "none" },
      diagnostics = {
        darker = false,
        undercurl = true,
        background = false,
      },
      -- Pure black canvas; opaque filled surfaces and one selection accent.
      colors = {
        black = "#000000",
        bg0 = "#000000", bg_d = "#0A0A0A", bg1 = "#141414",
        bg2 = "#1E1E1E", bg3 = "#2A2A2A",
        fg = "#D7E3FF", grey = "#53627A", light_grey = "#A9B9D6",
        blue = "#69AFFF", green = "#B8E986", purple = "#C7A6FF",
        red = "#FF8FA3", orange = "#FF9E64", yellow = "#FFD166", cyan = "#70D7FF",
      },
      highlights = {
        -- ── Standard Vim Syntax ────────────────────────────────────────
        Comment = { fg = "#61708A", fmt = "italic" },
        SpecialComment = { fg = "#61708A", fmt = "italic" },
        Constant = { fg = "#FACC15" },
        String = { fg = "#4ADE80" },
        Character = { fg = "#4ADE80" },
        Number = { fg = "#FF9E64" },
        Boolean = { fg = "#FF9E64", fmt = "bold" },
        Float = { fg = "#FF9E64" },
        Identifier = { fg = "#E2E8F0" },
        Function = { fg = "#38BDF8" },
        Statement = { fg = "#D946EF", fmt = "bold" },
        Conditional = { fg = "#C084FC", fmt = "bold" },
        Repeat = { fg = "#C084FC", fmt = "bold" },
        Label = { fg = "#FFD166", fmt = "bold" },
        Operator = { fg = "#70D7FF" },
        Keyword = { fg = "#D946EF", fmt = "bold" },
        Exception = { fg = "#FF2E4C", fmt = "bold" },
        PreProc = { fg = "#FF4D6D", fmt = "bold" },
        Include = { fg = "#E879F9", fmt = "bold" },
        Define = { fg = "#FF4D6D", fmt = "bold" },
        Macro = { fg = "#FF4D6D" },
        PreCondit = { fg = "#D946EF", fmt = "bold" },
        Type = { fg = "#FFD166" },
        StorageClass = { fg = "#D946EF", fmt = "bold" },
        Structure = { fg = "#FFD166", fmt = "bold" },
        Typedef = { fg = "#FFD166", fmt = "bold" },
        Special = { fg = "#FF4D6D" },
        SpecialChar = { fg = "#F97316" },
        Delimiter = { fg = "#94A3B8" },

        -- ── Treesitter Base Captures ───────────────────────────────────
        -- Variables & Members
        ["@variable"] = { fg = "#E2E8F0" },
        ["@variable.parameter"] = { fg = "#FF9E64" },
        ["@variable.member"] = { fg = "#C084FC" },
        ["@variable.builtin"] = { fg = "#FF4D6D" },
        ["@property"] = { fg = "#C084FC" },
        ["@field"] = { fg = "#C084FC" },

        -- Functions & Methods
        ["@function"] = { fg = "#38BDF8" },
        ["@function.call"] = { fg = "#38BDF8" },
        ["@function.method"] = { fg = "#22D3EE" },
        ["@function.method.call"] = { fg = "#22D3EE" },
        ["@function.builtin"] = { fg = "#FF4D6D" },
        ["@function.macro"] = { fg = "#FF4D6D" },
        ["@method"] = { fg = "#22D3EE" },
        ["@method.call"] = { fg = "#22D3EE" },
        ["@constructor"] = { fg = "#FFD166", fmt = "bold" },

        -- Types & Classes
        ["@type"] = { fg = "#FFD166" },
        ["@type.builtin"] = { fg = "#FBBF24", fmt = "bold" },
        ["@type.definition"] = { fg = "#FFD166", fmt = "bold" },
        ["@type.qualifier"] = { fg = "#D946EF", fmt = "bold" },
        ["@class"] = { fg = "#FFD166", fmt = "bold" },
        ["@interface"] = { fg = "#FFD166", fmt = "bold" },
        ["@struct"] = { fg = "#FFD166", fmt = "bold" },
        ["@enum"] = { fg = "#FFD166", fmt = "bold" },
        ["@enumMember"] = { fg = "#F59E0B" },

        -- Literals
        ["@string"] = { fg = "#4ADE80" },
        ["@string.regex"] = { fg = "#F97316" },
        ["@string.regexp"] = { fg = "#F97316" },
        ["@string.escape"] = { fg = "#F97316" },
        ["@string.special"] = { fg = "#4ADE80" },
        ["@character"] = { fg = "#4ADE80" },
        ["@character.special"] = { fg = "#F97316" },
        ["@number"] = { fg = "#FF9E64" },
        ["@number.float"] = { fg = "#FF9E64" },
        ["@float"] = { fg = "#FF9E64" },
        ["@boolean"] = { fg = "#FF9E64", fmt = "bold" },
        ["@constant"] = { fg = "#FACC15" },
        ["@constant.builtin"] = { fg = "#FACC15", fmt = "bold" },

        -- Keywords
        ["@keyword"] = { fg = "#D946EF", fmt = "bold" },
        ["@keyword.coroutine"] = { fg = "#D946EF", fmt = "bold" },
        ["@keyword.function"] = { fg = "#D946EF", fmt = "bold" },
        ["@keyword.operator"] = { fg = "#D946EF", fmt = "bold" },
        ["@keyword.import"] = { fg = "#E879F9", fmt = "bold" },
        ["@keyword.type"] = { fg = "#E879F9", fmt = "bold" },
        ["@keyword.modifier"] = { fg = "#D946EF", fmt = "bold" },
        ["@keyword.repeat"] = { fg = "#C084FC", fmt = "bold" },
        ["@keyword.conditional"] = { fg = "#C084FC", fmt = "bold" },
        ["@keyword.conditional.ternary"] = { fg = "#70D7FF" },
        ["@keyword.exception"] = { fg = "#FF2E4C", fmt = "bold" },
        ["@keyword.directive"] = { fg = "#FF4D6D", fmt = "bold" },
        ["@keyword.directive.define"] = { fg = "#FF4D6D", fmt = "bold" },
        ["@keyword.debug"] = { fg = "#D946EF", fmt = "bold" },
        ["@keyword.return"] = { fg = "#FF2E4C", fmt = "bold" },

        -- Comments
        ["@comment"] = { fg = "#61708A", fmt = "italic" },
        ["@comment.documentation"] = { fg = "#61708A", fmt = "italic" },
        ["@comment.error"] = { fg = "#FF2E4C", fmt = "bold,italic" },
        ["@comment.warning"] = { fg = "#FFD166", fmt = "bold,italic" },
        ["@comment.todo"] = { fg = "#000000", bg = "#FFD166", fmt = "bold" },
        ["@comment.note"] = { fg = "#38BDF8", fmt = "bold,italic" },

        -- Operators & Punctuation
        ["@operator"] = { fg = "#70D7FF" },
        ["@punctuation"] = { fg = "#94A3B8" },
        ["@punctuation.delimiter"] = { fg = "#94A3B8" },
        ["@punctuation.bracket"] = { fg = "#94A3B8" },
        ["@punctuation.special"] = { fg = "#70D7FF" },
        ["@attribute"] = { fg = "#C084FC" },
        ["@module"] = { fg = "#FACC15" },
        ["@module.builtin"] = { fg = "#FF4D6D" },
        ["@label"] = { fg = "#FFD166", fmt = "bold" },

        -- ── Python ────────────────────────────────────────────────────
        ["@variable.python"] = { fg = "#E2E8F0" },
        ["@variable.parameter.python"] = { fg = "#FF9E64" },
        ["@variable.member.python"] = { fg = "#C084FC" },
        ["@variable.builtin.python"] = { fg = "#FF4D6D" },
        ["@function.python"] = { fg = "#38BDF8" },
        ["@function.call.python"] = { fg = "#38BDF8" },
        ["@function.method.python"] = { fg = "#22D3EE" },
        ["@function.method.call.python"] = { fg = "#22D3EE" },
        ["@function.builtin.python"] = { fg = "#FF4D6D" },
        ["@type.python"] = { fg = "#FFD166" },
        ["@type.builtin.python"] = { fg = "#FBBF24", fmt = "bold" },
        ["@constructor.python"] = { fg = "#FFD166", fmt = "bold" },
        ["@string.python"] = { fg = "#4ADE80" },
        ["@string.documentation.python"] = { fg = "#61708A", fmt = "italic" },
        ["@number.python"] = { fg = "#FF9E64" },
        ["@boolean.python"] = { fg = "#FF9E64", fmt = "bold" },
        ["@constant.builtin.python"] = { fg = "#FACC15", fmt = "bold" },
        ["@keyword.python"] = { fg = "#D946EF", fmt = "bold" },
        ["@keyword.function.python"] = { fg = "#D946EF", fmt = "bold" },
        ["@keyword.import.python"] = { fg = "#E879F9", fmt = "bold" },
        ["@keyword.conditional.python"] = { fg = "#C084FC", fmt = "bold" },
        ["@keyword.repeat.python"] = { fg = "#C084FC", fmt = "bold" },
        ["@keyword.coroutine.python"] = { fg = "#D946EF", fmt = "bold" },
        ["@keyword.exception.python"] = { fg = "#FF2E4C", fmt = "bold" },
        ["@keyword.operator.python"] = { fg = "#D946EF", fmt = "bold" },
        ["@keyword.type.python"] = { fg = "#E879F9", fmt = "bold" },
        ["@keyword.debug.python"] = { fg = "#D946EF", fmt = "bold" },
        ["@keyword.return.python"] = { fg = "#FF2E4C", fmt = "bold" },
        ["@operator.python"] = { fg = "#70D7FF" },
        ["@punctuation.python"] = { fg = "#94A3B8" },
        ["@punctuation.special.python"] = { fg = "#70D7FF" },
        ["@module.python"] = { fg = "#FACC15" },
        ["@attribute.python"] = { fg = "#C084FC" },

        -- ── Lua ───────────────────────────────────────────────────────
        ["@variable.lua"] = { fg = "#E2E8F0" },
        ["@variable.parameter.lua"] = { fg = "#FF9E64" },
        ["@variable.member.lua"] = { fg = "#C084FC" },
        ["@variable.builtin.lua"] = { fg = "#FF4D6D" },
        ["@function.lua"] = { fg = "#38BDF8" },
        ["@function.call.lua"] = { fg = "#38BDF8" },
        ["@function.method.lua"] = { fg = "#22D3EE" },
        ["@function.method.call.lua"] = { fg = "#22D3EE" },
        ["@function.builtin.lua"] = { fg = "#FF4D6D" },
        ["@type.lua"] = { fg = "#FFD166" },
        ["@type.builtin.lua"] = { fg = "#FBBF24", fmt = "bold" },
        ["@constructor.lua"] = { fg = "#FFD166", fmt = "bold" },
        ["@string.lua"] = { fg = "#4ADE80" },
        ["@number.lua"] = { fg = "#FF9E64" },
        ["@boolean.lua"] = { fg = "#FF9E64", fmt = "bold" },
        ["@keyword.lua"] = { fg = "#D946EF", fmt = "bold" },
        ["@keyword.function.lua"] = { fg = "#D946EF", fmt = "bold" },
        ["@keyword.conditional.lua"] = { fg = "#C084FC", fmt = "bold" },
        ["@keyword.repeat.lua"] = { fg = "#C084FC", fmt = "bold" },
        ["@keyword.operator.lua"] = { fg = "#D946EF", fmt = "bold" },
        ["@keyword.return.lua"] = { fg = "#FF2E4C", fmt = "bold" },
        ["@operator.lua"] = { fg = "#70D7FF" },
        ["@punctuation.lua"] = { fg = "#94A3B8" },
        ["@module.lua"] = { fg = "#FACC15" },
        ["@property.lua"] = { fg = "#C084FC" },

        -- ── C ─────────────────────────────────────────────────────────
        ["@variable.c"] = { fg = "#E2E8F0" },
        ["@variable.parameter.c"] = { fg = "#FF9E64" },
        ["@variable.member.c"] = { fg = "#C084FC" },
        ["@variable.builtin.c"] = { fg = "#FF4D6D" },
        ["@function.c"] = { fg = "#38BDF8" },
        ["@function.call.c"] = { fg = "#38BDF8" },
        ["@function.builtin.c"] = { fg = "#FF4D6D" },
        ["@function.macro.c"] = { fg = "#FF4D6D" },
        ["@type.c"] = { fg = "#FFD166" },
        ["@type.builtin.c"] = { fg = "#FBBF24", fmt = "bold" },
        ["@type.qualifier.c"] = { fg = "#D946EF", fmt = "bold" },
        ["@string.c"] = { fg = "#4ADE80" },
        ["@number.c"] = { fg = "#FF9E64" },
        ["@boolean.c"] = { fg = "#FF9E64", fmt = "bold" },
        ["@constant.c"] = { fg = "#FACC15" },
        ["@constant.builtin.c"] = { fg = "#FACC15", fmt = "bold" },
        ["@keyword.c"] = { fg = "#D946EF", fmt = "bold" },
        ["@keyword.type.c"] = { fg = "#E879F9", fmt = "bold" },
        ["@keyword.directive.c"] = { fg = "#FF4D6D", fmt = "bold" },
        ["@keyword.directive.define.c"] = { fg = "#FF4D6D", fmt = "bold" },
        ["@keyword.conditional.c"] = { fg = "#C084FC", fmt = "bold" },
        ["@keyword.repeat.c"] = { fg = "#C084FC", fmt = "bold" },
        ["@keyword.return.c"] = { fg = "#FF2E4C", fmt = "bold" },
        ["@operator.c"] = { fg = "#70D7FF" },
        ["@punctuation.c"] = { fg = "#94A3B8" },

        -- ── C++ ───────────────────────────────────────────────────────
        ["@variable.cpp"] = { fg = "#E2E8F0" },
        ["@variable.parameter.cpp"] = { fg = "#FF9E64" },
        ["@variable.member.cpp"] = { fg = "#C084FC" },
        ["@variable.builtin.cpp"] = { fg = "#FF4D6D" },
        ["@function.cpp"] = { fg = "#38BDF8" },
        ["@function.call.cpp"] = { fg = "#38BDF8" },
        ["@function.method.cpp"] = { fg = "#22D3EE" },
        ["@function.method.call.cpp"] = { fg = "#22D3EE" },
        ["@function.builtin.cpp"] = { fg = "#FF4D6D" },
        ["@constructor.cpp"] = { fg = "#FFD166", fmt = "bold" },
        ["@type.cpp"] = { fg = "#FFD166" },
        ["@type.builtin.cpp"] = { fg = "#FBBF24", fmt = "bold" },
        ["@type.qualifier.cpp"] = { fg = "#D946EF", fmt = "bold" },
        ["@string.cpp"] = { fg = "#4ADE80" },
        ["@number.cpp"] = { fg = "#FF9E64" },
        ["@boolean.cpp"] = { fg = "#FF9E64", fmt = "bold" },
        ["@constant.cpp"] = { fg = "#FACC15" },
        ["@constant.builtin.cpp"] = { fg = "#FACC15", fmt = "bold" },
        ["@keyword.cpp"] = { fg = "#D946EF", fmt = "bold" },
        ["@keyword.type.cpp"] = { fg = "#E879F9", fmt = "bold" },
        ["@keyword.directive.cpp"] = { fg = "#FF4D6D", fmt = "bold" },
        ["@keyword.conditional.cpp"] = { fg = "#C084FC", fmt = "bold" },
        ["@keyword.repeat.cpp"] = { fg = "#C084FC", fmt = "bold" },
        ["@keyword.return.cpp"] = { fg = "#FF2E4C", fmt = "bold" },
        ["@keyword.exception.cpp"] = { fg = "#FF2E4C", fmt = "bold" },
        ["@operator.cpp"] = { fg = "#70D7FF" },
        ["@punctuation.cpp"] = { fg = "#94A3B8" },

        -- ── LSP Semantic Tokens ────────────────────────────────────────
        ["@lsp.type.variable"] = { fg = "#E2E8F0" },
        ["@lsp.type.parameter"] = { fg = "#FF9E64" },
        ["@lsp.type.property"] = { fg = "#C084FC" },
        ["@lsp.type.function"] = { fg = "#38BDF8" },
        ["@lsp.type.method"] = { fg = "#22D3EE" },
        ["@lsp.type.class"] = { fg = "#FFD166", fmt = "bold" },
        ["@lsp.type.type"] = { fg = "#FFD166" },
        ["@lsp.type.struct"] = { fg = "#FFD166" },
        ["@lsp.type.interface"] = { fg = "#FFD166" },
        ["@lsp.type.enum"] = { fg = "#FFD166" },
        ["@lsp.type.enumMember"] = { fg = "#F59E0B" },
        ["@lsp.type.macro"] = { fg = "#FF4D6D" },
        ["@lsp.type.namespace"] = { fg = "#FACC15" },
        ["@lsp.type.string"] = { fg = "#4ADE80" },
        ["@lsp.type.number"] = { fg = "#FF9E64" },
        ["@lsp.type.keyword"] = { fg = "#D946EF", fmt = "bold" },
        ["@lsp.type.comment"] = { fg = "#61708A", fmt = "italic" },
        ["@lsp.type.decorator"] = { fg = "#C084FC" },
        ["@lsp.typemod.variable.defaultLibrary"] = { fg = "#FF4D6D" },
        ["@lsp.typemod.function.defaultLibrary"] = { fg = "#FF4D6D" },
        ["@lsp.typemod.method.defaultLibrary"] = { fg = "#22D3EE" },
        ["@lsp.typemod.class.defaultLibrary"] = { fg = "#FFD166" },
        ["@lsp.typemod.type.defaultLibrary"] = { fg = "#FFD166" },
        ["@lsp.typemod.keyword.async"] = { fg = "#D946EF", fmt = "bold" },
        ["@lsp.typemod.function.declaration"] = { fg = "#38BDF8" },
        ["@lsp.typemod.method.declaration"] = { fg = "#22D3EE" },

        -- Language-specific LSP mappings (Python / C / C++)
        ["@lsp.type.variable.python"] = { fg = "#E2E8F0" },
        ["@lsp.type.parameter.python"] = { fg = "#FF9E64" },
        ["@lsp.type.property.python"] = { fg = "#C084FC" },
        ["@lsp.type.function.python"] = { fg = "#38BDF8" },
        ["@lsp.type.method.python"] = { fg = "#22D3EE" },
        ["@lsp.type.class.python"] = { fg = "#FFD166", fmt = "bold" },
        ["@lsp.type.type.python"] = { fg = "#FFD166" },
        ["@lsp.type.namespace.python"] = { fg = "#FACC15" },
        ["@lsp.type.decorator.python"] = { fg = "#C084FC" },
        ["@lsp.typemod.variable.defaultLibrary.python"] = { fg = "#FF4D6D" },
        ["@lsp.typemod.class.defaultLibrary.python"] = { fg = "#FFD166" },
        ["@lsp.type.variable.c"] = { fg = "#E2E8F0" },
        ["@lsp.type.variable.cpp"] = { fg = "#E2E8F0" },
        ["@lsp.type.parameter.c"] = { fg = "#FF9E64" },
        ["@lsp.type.parameter.cpp"] = { fg = "#FF9E64" },
        ["@lsp.type.property.c"] = { fg = "#C084FC" },
        ["@lsp.type.property.cpp"] = { fg = "#C084FC" },
        ["@lsp.type.function.c"] = { fg = "#38BDF8" },
        ["@lsp.type.function.cpp"] = { fg = "#38BDF8" },
        ["@lsp.type.method.cpp"] = { fg = "#22D3EE" },
        ["@lsp.type.class.cpp"] = { fg = "#FFD166", fmt = "bold" },
        ["@lsp.type.type.c"] = { fg = "#FFD166" },
        ["@lsp.type.type.cpp"] = { fg = "#FFD166" },
        ["@lsp.type.enum.c"] = { fg = "#FFD166" },
        ["@lsp.type.enum.cpp"] = { fg = "#FFD166" },
        ["@lsp.type.enumMember.c"] = { fg = "#F59E0B" },
        ["@lsp.type.enumMember.cpp"] = { fg = "#F59E0B" },
        ["@lsp.type.macro.c"] = { fg = "#FF4D6D" },
        ["@lsp.type.macro.cpp"] = { fg = "#FF4D6D" },
        ["@lsp.type.namespace.cpp"] = { fg = "#FACC15" },

        -- ── Markdown & Documentation ──────────────────────────────────
        -- Treesitter markup
        ["@markup.heading"] = { fg = "#69AFFF", fmt = "bold" },
        ["@markup.heading.1"] = { fg = "#69AFFF", fmt = "bold" },
        ["@markup.heading.2"] = { fg = "#C7A6FF", fmt = "bold" },
        ["@markup.heading.3"] = { fg = "#7FE3C2", fmt = "bold" },
        ["@markup.heading.4"] = { fg = "#70D7FF", fmt = "bold" },
        ["@markup.heading.5"] = { fg = "#FF9E64", fmt = "bold" },
        ["@markup.heading.6"] = { fg = "#A9B9D6", fmt = "bold" },
        ["@markup.heading.1.marker"] = { fg = "#53627A", fmt = "bold" },
        ["@markup.heading.2.marker"] = { fg = "#53627A", fmt = "bold" },
        ["@markup.heading.3.marker"] = { fg = "#53627A", fmt = "bold" },
        ["@markup.heading.4.marker"] = { fg = "#53627A", fmt = "bold" },
        ["@markup.heading.5.marker"] = { fg = "#53627A", fmt = "bold" },
        ["@markup.heading.6.marker"] = { fg = "#53627A", fmt = "bold" },
        ["@markup.strong"] = { fg = "#D7E3FF", fmt = "bold" },
        ["@markup.italic"] = { fg = "#D7E3FF", fmt = "italic" },
        ["@markup.strikethrough"] = { fg = "#53627A", fmt = "strikethrough" },
        ["@markup.raw"] = { fg = "#B8E986" },
        ["@markup.raw.inline"] = { fg = "#B8E986", bg = "#141414" },
        ["@markup.raw.block"] = { fg = "#D7E3FF" },
        ["@markup.link"] = { fg = "#69AFFF" },
        ["@markup.link.label"] = { fg = "#69AFFF" },
        ["@markup.link.url"] = { fg = "#70D7FF", fmt = "underline" },
        ["@markup.list"] = { fg = "#70D7FF" },
        ["@markup.list.checked"] = { fg = "#7FE3C2" },
        ["@markup.list.unchecked"] = { fg = "#53627A" },
        ["@markup.quote"] = { fg = "#61708A", fmt = "italic" },
        ["@markup.math"] = { fg = "#FF9E64" },

        -- Vim native markdown groups
        markdownH1 = { fg = "#69AFFF", fmt = "bold" },
        markdownH2 = { fg = "#C7A6FF", fmt = "bold" },
        markdownH3 = { fg = "#7FE3C2", fmt = "bold" },
        markdownH4 = { fg = "#70D7FF", fmt = "bold" },
        markdownH5 = { fg = "#FF9E64", fmt = "bold" },
        markdownH6 = { fg = "#A9B9D6", fmt = "bold" },
        markdownBold = { fg = "#D7E3FF", fmt = "bold" },
        markdownItalic = { fg = "#D7E3FF", fmt = "italic" },
        markdownCode = { fg = "#B8E986" },
        markdownCodeBlock = { fg = "#D7E3FF" },
        markdownLinkText = { fg = "#69AFFF" },
        markdownUrl = { fg = "#70D7FF", fmt = "underline" },
        markdownRule = { fg = "#354357", fmt = "bold" },
        markdownBlockquote = { fg = "#61708A", fmt = "italic" },
        markdownListMarker = { fg = "#70D7FF" },

        -- Render-Markdown plugin highlights
        RenderMarkdownH1 = { fg = "#69AFFF", fmt = "bold" },
        RenderMarkdownH2 = { fg = "#C7A6FF", fmt = "bold" },
        RenderMarkdownH3 = { fg = "#7FE3C2", fmt = "bold" },
        RenderMarkdownH4 = { fg = "#70D7FF", fmt = "bold" },
        RenderMarkdownH5 = { fg = "#FF9E64", fmt = "bold" },
        RenderMarkdownH6 = { fg = "#A9B9D6", fmt = "bold" },
        RenderMarkdownH1Bg = { bg = "#10151C" },
        RenderMarkdownH2Bg = { bg = "#0E141D" },
        RenderMarkdownH3Bg = { bg = "#0A0F16" },
        RenderMarkdownH4Bg = { bg = "#070B10" },
        RenderMarkdownH5Bg = { bg = "NONE" },
        RenderMarkdownH6Bg = { bg = "NONE" },
        RenderMarkdownCode = { bg = "#0A0A0A" },
        RenderMarkdownCodeInline = { bg = "#141414", fg = "#B8E986" },
        RenderMarkdownBullet = { fg = "#70D7FF" },
        RenderMarkdownTableHead = { fg = "#69AFFF", fmt = "bold" },
        RenderMarkdownTableRow = { fg = "#354357" },
        RenderMarkdownTableFill = { fg = "#1E2836" },
        RenderMarkdownQuote = { fg = "#61708A", fmt = "italic" },
        RenderMarkdownLink = { fg = "#69AFFF" },
        RenderMarkdownWikiLink = { fg = "#70D7FF" },
        RenderMarkdownTodo = { fg = "#FF9E64" },
        RenderMarkdownChecked = { fg = "#7FE3C2" },
        RenderMarkdownUnchecked = { fg = "#53627A" },

        -- ── Custom Surface & Editor Chrome Groups ───────────────────────
        BlackBrand = { fg = "#FF2E4C", fmt = "bold" },
        BlackLabel = { fg = "#FF4D6D", fmt = "bold" },
        BlackMuted = { fg = "#A8606B" },
        BlackKey = { fg = "#FF4D6D", bg = "#4A0E17", fmt = "bold" },
        NoiceCmdlineIcon = { fg = "#FF2E4C" },
        LineNr = { fg = "#555555", bg = "NONE" },
        CursorLine = { bg = "#180A0E" },
        CursorLineNr = { fg = "#FF2E4C", bg = "NONE", fmt = "bold" },
        Cursor = { fg = "#000000", bg = "#FF2E4C" },
        lCursor = { fg = "#000000", bg = "#FF2E4C" },
        MatchParen = { fg = "#FFFFFF", bg = "#5C1522", fmt = "bold,underline" },
        Substitute = { bg = "#FF2E4C", fg = "$bg0", fmt = "bold" },
        Folded = { fg = "$grey", bg = "$bg1", fmt = "italic" },
        FoldColumn = { fg = "$grey", bg = "NONE" },
        EndOfBuffer = { fg = "$bg0", bg = "NONE" },
        StatusLine = { bg = "$bg1", fg = "$fg" },
        StatusLineNC = { bg = "$bg_d", fg = "$grey" },
        WinBar = { bg = "$bg0", fg = "$light_grey", fmt = "bold" },
        WinBarNC = { bg = "$bg0", fg = "$grey" },
        TabLine = { bg = "$bg1", fg = "$grey" },
        TabLineFill = { bg = "$bg0" },
        TabLineSel = { bg = "#3D0D14", fg = "$fg", fmt = "bold" },
        FloatBorder = { bg = "$bg1", fg = "#5C1522" },
        FloatTitle = { bg = "$bg1", fg = "#FF2E4C", fmt = "bold" },
        DiagnosticError = { fg = "#FF8FA3" },
        DiagnosticWarn = { fg = "#FFD166" },
        DiagnosticInfo = { fg = "#70D7FF" },
        DiagnosticHint = { fg = "#7FE3C2" },
        SnacksDashboardFile = { fg = "#FFFFFF" },
        SnacksDashboardDesc = { fg = "#D7E3FF" },
        SnacksDashboardIcon = { fg = "#FF4D6D" },
        SnacksDashboardFooter = { fg = "#A8606B" },
        SnacksDashboardHeader = { fg = "#FF2E4C", fmt = "bold" },
        SnacksDashboardKey = { fg = "#FF4D6D", fmt = "bold" },
        SnacksDashboardSpecial = { fg = "#FF2E4C", fmt = "bold" },
        SnacksDashboardDir = { fg = "#A8606B" },
        WhichKey = { fg = "#FF4D6D" },
        WhichKeyGroup = { fg = "#FF2E4C" },
        WhichKeyDesc = { fg = "$fg" },
        WinSeparator = { fg = "#3D101A", bg = "$bg0" },
        Pmenu = { bg = "$bg1", fg = "$fg" },
        PmenuSel = { bg = "#4A0E17", fg = "#FF4D6D", fmt = "bold" },
        PmenuBorder = { fg = "#5C1522", bg = "$bg1" },
        PmenuSbar = { bg = "#0A0A0E" },
        PmenuThumb = { bg = "#5C1522" },
        CmpItemAbbr = { fg = "$fg" },
        CmpItemKind = { fg = "#FF4D6D" },
        CmpItemAbbrMatch = { fg = "#FFFFFF", fmt = "bold,underline" },
        CmpItemAbbrMatchFuzzy = { fg = "#FF4D6D", fmt = "bold" },
        CmpItemMenu = { fg = "$light_grey" },
        LspSignatureActiveParameter = { fg = "#FFFFFF", bg = "#4A0E17", fmt = "bold,underline" },
        BufferLineFill = { bg = "#0A0A0E" },
        BufferLineBackground = { bg = "#0A0A0E", fg = "#7A5A62" },
        BufferLineBufferSelected = { bg = "#3D0D14", fg = "#FFFFFF", fmt = "bold" },
        BufferLineIndicatorSelected = { bg = "#3D0D14", fg = "#FF2E4C" },
        SnacksIndent = { fg = "#2A0E15" },
        SnacksIndentScope = { fg = "#FF2E4C" },

        -- ── Git Gutter & Diffs ─────────────────────────────────────────
        GitSignsAdd = { fg = "#7FE3C2" },
        GitSignsChange = { fg = "#FFD166" },
        GitSignsDelete = { fg = "#FF8FA3" },
        GitSignsAddNr = { fg = "#7FE3C2" },
        GitSignsChangeNr = { fg = "#FFD166" },
        GitSignsDeleteNr = { fg = "#FF8FA3" },
        DiffAdd = { bg = "#0A241A", fg = "#7FE3C2" },
        DiffChange = { bg = "#261C08", fg = "#FFD166" },
        DiffDelete = { bg = "#2B0E18", fg = "#FF8FA3" },
        DiffText = { bg = "#4A3610", fg = "#FFE29A", fmt = "bold" },

        -- ── Search & Selection ─────────────────────────────────────────
        Search = { bg = "#2D234D", fg = "#E9D7FF" },
        IncSearch = { bg = "#F7768E", fg = "#000000", fmt = "bold" },
        CurSearch = { bg = "#FF9E64", fg = "#000000", fmt = "bold" },
        Visual = { bg = "#24204A", fg = "$fg" },
        VisualNOS = { bg = "#24204A", fg = "$fg" },

        -- ── Diagnostics Undercurls ─────────────────────────────────────
        DiagnosticUnderlineError = { sp = "#FF8FA3", fmt = "undercurl", bg = "NONE" },
        DiagnosticUnderlineWarn = { sp = "#FFD166", fmt = "undercurl", bg = "NONE" },
        DiagnosticUnderlineInfo = { sp = "#70D7FF", fmt = "undercurl", bg = "NONE" },
        DiagnosticUnderlineHint = { sp = "#7FE3C2", fmt = "undercurl", bg = "NONE" },
        DiagnosticUnderlineOk = { sp = "#B8E986", fmt = "undercurl", bg = "NONE" },

        -- ── Float Shadows & Treesitter Context ─────────────────────────
        FloatShadow = { bg = "$bg0" },
        FloatShadowThrough = { bg = "$bg0" },
        TreesitterContext = { bg = "$bg_d" },
        TreesitterContextLineNumber = { fg = "$grey", bg = "$bg_d" },

        -- ── Missing Polish Highlights ──────────────────────────────────
        WildMenu = { bg = "$bg2", fg = "$purple", fmt = "bold" },
        SpellBad = { sp = "$red", fmt = "undercurl" },
        SpellCap = { sp = "$yellow", fmt = "undercurl" },
        SpellRare = { sp = "$cyan", fmt = "undercurl" },
        SpellLocal = { sp = "$green", fmt = "undercurl" },
        Todo = { bg = "$yellow", fg = "$bg0", fmt = "bold" },
        NonText = { fg = "#61708A" },
        Whitespace = { fg = "#4A4A5A" },
        Directory = { fg = "#FF4D6D", fmt = "bold" },
        Title = { fg = "#FF2E4C", fmt = "bold" },
        Question = { fg = "$green", fmt = "bold" },
        MoreMsg = { fg = "$green", fmt = "bold" },
        WarningMsg = { fg = "$yellow", fmt = "bold" },
        ErrorMsg = { fg = "$red", fmt = "bold" },
        MsgArea = { fg = "$fg", bg = "$bg0" },
        MsgSeparator = { fg = "$bg3", bg = "$bg0" },
        NormalNC = { bg = "$bg_d" },
      },
    },
    config = function(_, opts)
      opts.highlights = vim.tbl_deep_extend("force", opts.highlights or {}, require("config.surfaces").highlights())
      require("onedark").setup(opts)
      require("onedark").load()
    end,
  },
}
